<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AllocationController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\BudgetController;
use App\Http\Controllers\ChargeCategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ContextController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExpenseCategoryController;
use App\Http\Controllers\ExpenseCommitmentController;
use App\Http\Controllers\ExpenseDashboardController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\FinancialAccountController;
use App\Http\Controllers\FinancialDocumentController;
use App\Http\Controllers\FinancialExerciseController;
use App\Http\Controllers\FundCallController;
use App\Http\Controllers\FundCallScheduleController;
use App\Http\Controllers\GovernanceActionController;
use App\Http\Controllers\GovernanceController;
use App\Http\Controllers\GovernanceDocumentController;
use App\Http\Controllers\GovernanceMandateController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\InvitationController;
use App\Http\Controllers\LotController;
use App\Http\Controllers\MaintenanceAttachmentController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\MaintenanceQuotationController;
use App\Http\Controllers\MaintenanceRequestActionController;
use App\Http\Controllers\MaintenanceWorkOrderController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OccupancyController;
use App\Http\Controllers\OnboardingController;
use App\Http\Controllers\OwnerFinancePortalController;
use App\Http\Controllers\OwnerGovernanceController;
use App\Http\Controllers\OwnershipController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PreventiveMaintenanceController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReceiptController;
use App\Http\Controllers\ResidenceController;
use App\Http\Controllers\ResidenceDocumentController;
use App\Http\Controllers\ResidentMaintenanceController;
use App\Http\Controllers\ResidentPortalController;
use App\Http\Controllers\StructureController;
use App\Http\Controllers\SupplierContractAttachmentController;
use App\Http\Controllers\SupplierContractController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\SupplierCreditNoteController;
use App\Http\Controllers\SupplierInvoiceController;
use App\Http\Controllers\SupplierPayableController;
use App\Http\Controllers\SupplierSettlementController;
use App\Http\Controllers\SupplierStatementController;
use App\Http\Controllers\TeamController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');
Route::get('/verify/receipts/{token}', [ReceiptController::class, 'verify'])->middleware('throttle:30,1')->name('receipts.verify');
Route::get('/verify/financial-documents/{token}', [FinancialDocumentController::class, 'verify'])->middleware('throttle:30,1')->name('financial-documents.verify');
Route::get('/invitations/{token}', [InvitationController::class, 'show'])->name('invitations.show');
Route::middleware('guest')->group(function () {
    Route::get('/invitations/{token}/register', [InvitationController::class, 'register'])->name('invitations.register');
    Route::post('/invitations/{token}/register', [InvitationController::class, 'store'])->name('invitations.register.store');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/onboarding', [OnboardingController::class, 'index'])->name('onboarding.index');
    Route::post('/onboarding/organization', [OnboardingController::class, 'organization'])->name('onboarding.organization');
    Route::post('/onboarding/residence', [OnboardingController::class, 'residence'])->name('onboarding.residence');
    Route::post('/onboarding/skip/{step}', [OnboardingController::class, 'skip'])->name('onboarding.skip');
    Route::post('/onboarding/acknowledge-ownership', [OnboardingController::class, 'acknowledgeOwnership'])->name('onboarding.ownership.acknowledge');
    Route::post('/onboarding/defer-allocations', [OnboardingController::class, 'deferAllocations'])->name('onboarding.allocations.defer');
    Route::post('/onboarding/activate', [OnboardingController::class, 'activate'])->name('onboarding.activate');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::post('/invitations/{token}/accept', [InvitationController::class, 'accept'])->name('invitations.accept');

    Route::middleware(['verified', 'tenant'])->group(function () {
        Route::get('/dashboard', DashboardController::class)->name('dashboard');
        Route::put('/context/organizations/{organization}', [ContextController::class, 'organization'])->name('context.organization');
        Route::put('/context/residences/{residence}', [ContextController::class, 'residence'])->name('context.residence');

        Route::middleware('tenant.permission:view_residences')->group(function () {
            Route::get('/residences', [ResidenceController::class, 'index'])->name('residences.index');
            Route::get('/residences/{residence}', [ResidenceController::class, 'show'])->name('residences.show');
        });
        Route::middleware('tenant.permission:create_residences')->group(function () {
            Route::get('/residences/create/new', [ResidenceController::class, 'create'])->name('residences.create');
            Route::post('/residences', [ResidenceController::class, 'store'])->name('residences.store');
        });
        Route::middleware('tenant.permission:edit_residences')->group(function () {
            Route::get('/residences/{residence}/edit', [ResidenceController::class, 'edit'])->name('residences.edit');
            Route::put('/residences/{residence}', [ResidenceController::class, 'update'])->name('residences.update');
            Route::delete('/residences/{residence}/logo', [ResidenceController::class, 'removeLogo'])->name('residences.logo.destroy');
            Route::post('/residences/{residence}/archive', [ResidenceController::class, 'archive'])->name('residences.archive');
            Route::post('/residences/{residence}/restore', [ResidenceController::class, 'restore'])->name('residences.restore');
        });

        Route::middleware('tenant.permission:manage_property_structure')->group(function () {
            Route::get('/structure', [StructureController::class, 'index'])->name('structure.index');
            Route::get('/lots/{lot}', [LotController::class, 'show'])->name('lots.show');
            Route::post('/structure/buildings', [StructureController::class, 'building'])->name('buildings.store');
            Route::post('/structure/buildings/{building}/entrances', [StructureController::class, 'entrance'])->name('entrances.store');
            Route::post('/structure/buildings/{building}/floors', [StructureController::class, 'floor'])->name('floors.store');
            Route::post('/structure/lots', [StructureController::class, 'lot'])->name('lots.store');
            Route::put('/structure/lots/{lot}', [StructureController::class, 'updateLot'])->name('lots.update');
            Route::post('/structure/lots/bulk', [StructureController::class, 'bulk'])->name('lots.bulk');
        });
        Route::get('/search/contacts', [LotController::class, 'contacts'])->middleware('tenant.permission:manage_contacts')->name('search.contacts');
        Route::middleware('tenant.permission:manage_contacts')->group(function () {
            Route::get('/contacts', [ContactController::class, 'index'])->name('contacts.index');
            Route::post('/contacts', [ContactController::class, 'store'])->name('contacts.store');
            Route::get('/contacts/{contact}', [ContactController::class, 'show'])->name('contacts.show');
            Route::put('/contacts/{contact}', [ContactController::class, 'update'])->name('contacts.update');
            Route::post('/contacts/{contact}/users/{user}', [ContactController::class, 'linkUser'])->name('contacts.users.link');
            Route::delete('/contacts/{contact}/users/{user}', [ContactController::class, 'unlinkUser'])->name('contacts.users.unlink');
        });
        Route::post('/lots/{lot}/ownership-transfer', [OwnershipController::class, 'transfer'])->middleware('tenant.permission:manage_ownerships')->name('ownerships.transfer');
        Route::post('/lots/{lot}/occupancies', [OccupancyController::class, 'store'])->middleware('tenant.permission:manage_occupancies')->name('occupancies.store');
        Route::post('/lots/{lot}/occupancies/{occupancy}/close', [OccupancyController::class, 'close'])->middleware('tenant.permission:manage_occupancies')->name('occupancies.close');
        Route::middleware('tenant.permission:manage_allocation_keys')->group(function () {
            Route::get('/allocations', [AllocationController::class, 'index'])->name('allocations.index');
            Route::post('/allocations', [AllocationController::class, 'store'])->name('allocations.store');
            Route::put('/allocations/{allocationKey}/values', [AllocationController::class, 'values'])->name('allocations.values');
            Route::post('/allocations/{allocationKey}/bulk', [AllocationController::class, 'bulk'])->name('allocations.bulk');
        });
        Route::middleware('tenant.permission:import_data')->group(function () {
            Route::get('/imports', [ImportController::class, 'index'])->name('imports.index');
            Route::post('/imports', [ImportController::class, 'upload'])->name('imports.upload');
            Route::get('/imports/{batch}/map', [ImportController::class, 'map'])->name('imports.map');
            Route::post('/imports/{batch}/confirm', [ImportController::class, 'confirm'])->name('imports.confirm');
            Route::get('/imports/{batch}/errors', [ImportController::class, 'errors'])->name('imports.errors');
            Route::post('/imports/{batch}/rollback', [ImportController::class, 'rollback'])->name('imports.rollback');
            Route::get('/import-templates/{type}', [ImportController::class, 'template'])->name('imports.template');
        });
        Route::get('/activity', ActivityController::class)->middleware('tenant.permission:view_activity_logs')->name('activity.index');
        Route::get('/my-finances', OwnerFinancePortalController::class)->name('owner-finance.index');
        Route::get('/my-finances/lots/{lot}/statement.pdf', [OwnerFinancePortalController::class, 'statement'])->name('owner-finance.statement');
        Route::get('/finance/receipts/{document}', [ReceiptController::class, 'download'])->name('receipts.download');
        Route::middleware('tenant.permission:view_finance')->group(function () {
            Route::get('/finance', [FinanceController::class, 'index'])->name('finance.index');
            Route::get('/finance/search', [FinanceController::class, 'search'])->name('finance.search');
            Route::get('/finance/fund-calls', [FundCallController::class, 'index'])->name('fund-calls.index');
            Route::get('/finance/fund-calls/{fundCall}', [FundCallController::class, 'show'])->name('fund-calls.show');
            Route::get('/finance/fund-calls/{fundCall}/pdf', [FundCallController::class, 'pdf'])->name('fund-calls.pdf');
            Route::get('/finance/payments', [PaymentController::class, 'index'])->name('payments.index');
            Route::get('/finance/payments/{payment}', [PaymentController::class, 'show'])->name('payments.show');
        });
        Route::middleware('tenant.permission:manage_financial_exercises')->group(function () {
            Route::get('/finance/exercises', [FinancialExerciseController::class, 'index'])->name('financial-exercises.index');
            Route::post('/finance/exercises', [FinancialExerciseController::class, 'store'])->name('financial-exercises.store');
            Route::put('/finance/exercises/{exercise}', [FinancialExerciseController::class, 'update'])->name('financial-exercises.update');
            Route::post('/finance/exercises/{exercise}/transition', [FinancialExerciseController::class, 'transition'])->name('financial-exercises.transition');
        });
        Route::middleware('tenant.permission:manage_financial_accounts')->group(function () {
            Route::get('/finance/accounts', [FinancialAccountController::class, 'index'])->name('financial-accounts.index');
            Route::post('/finance/accounts', [FinancialAccountController::class, 'store'])->name('financial-accounts.store');
            Route::put('/finance/accounts/{account}', [FinancialAccountController::class, 'update'])->name('financial-accounts.update');
            Route::post('/finance/accounts/{account}/archive', [FinancialAccountController::class, 'archive'])->name('financial-accounts.archive');
        });
        Route::middleware('tenant.permission:manage_charge_categories')->group(function () {
            Route::get('/finance/categories', [ChargeCategoryController::class, 'index'])->name('charge-categories.index');
            Route::post('/finance/categories', [ChargeCategoryController::class, 'store'])->name('charge-categories.store');
            Route::put('/finance/categories/{category}', [ChargeCategoryController::class, 'update'])->name('charge-categories.update');
            Route::post('/finance/categories/seed', [ChargeCategoryController::class, 'seed'])->name('charge-categories.seed');
        });
        Route::middleware('tenant.permission:create_fund_calls')->group(function () {
            Route::get('/finance/fund-calls/create/new', [FundCallController::class, 'create'])->name('fund-calls.create');
            Route::post('/finance/fund-calls', [FundCallController::class, 'store'])->name('fund-calls.store');
            Route::get('/finance/fund-calls/{fundCall}/edit', [FundCallController::class, 'edit'])->name('fund-calls.edit');
            Route::put('/finance/fund-calls/{fundCall}', [FundCallController::class, 'update'])->name('fund-calls.update');
            Route::get('/finance/schedules', [FundCallScheduleController::class, 'index'])->name('fund-call-schedules.index');
            Route::post('/finance/schedules', [FundCallScheduleController::class, 'store'])->name('fund-call-schedules.store');
            Route::put('/finance/schedules/{schedule}', [FundCallScheduleController::class, 'update'])->name('fund-call-schedules.update');
        });
        Route::post('/finance/fund-calls/{fundCall}/validate', [FundCallController::class, 'validateCall'])->middleware('tenant.permission:validate_fund_calls')->name('fund-calls.validate');
        Route::post('/finance/fund-calls/{fundCall}/cancel', [FundCallController::class, 'cancel'])->middleware('tenant.permission:cancel_fund_calls')->name('fund-calls.cancel');
        Route::middleware('tenant.permission:create_payments')->group(function () {
            Route::get('/finance/payments/create/new', [PaymentController::class, 'create'])->name('payments.create');
            Route::post('/finance/payments', [PaymentController::class, 'store'])->name('payments.store');
            Route::get('/finance/payments/{payment}/edit', [PaymentController::class, 'edit'])->name('payments.edit');
            Route::put('/finance/payments/{payment}', [PaymentController::class, 'update'])->name('payments.update');
        });
        Route::post('/finance/payments/{payment}/validate', [PaymentController::class, 'validatePayment'])->middleware('tenant.permission:validate_payments')->name('payments.validate');
        Route::post('/finance/payments/{payment}/allocate', [PaymentController::class, 'allocate'])->middleware('tenant.permission:allocate_credit')->name('payments.allocate');
        Route::post('/finance/payments/{payment}/identify-payer', [PaymentController::class, 'identifyPayer'])->middleware('tenant.permission:allocate_credit')->name('payments.identify-payer');
        Route::post('/finance/payments/{payment}/reverse', [PaymentController::class, 'reverse'])->middleware('tenant.permission:reverse_payments')->name('payments.reverse');
        Route::post('/finance/payments/{payment}/receipt/retry', [ReceiptController::class, 'retry'])->middleware('tenant.permission:validate_payments')->name('receipts.retry');
        Route::get('/finance/outstanding', [FinanceController::class, 'outstanding'])->middleware('tenant.permission:view_outstanding')->name('finance.outstanding');
        Route::get('/finance/statements', [FinanceController::class, 'statements'])->middleware('tenant.permission:view_statements')->name('finance.statements');
        Route::get('/finance/statements/pdf', [FinanceController::class, 'statementPdf'])->middleware('tenant.permission:export_finance')->name('finance.statements.pdf');
        Route::get('/finance/statements/csv', [FinanceController::class, 'statementCsv'])->middleware('tenant.permission:export_finance')->name('finance.statements.csv');
        Route::get('/finance/outstanding/export', [FinanceController::class, 'exportOutstanding'])->middleware('tenant.permission:export_finance')->name('finance.outstanding.export');

        Route::get('/resident', [ResidentPortalController::class, 'index'])->name('portal.index');
        Route::get('/resident/maintenance', [ResidentMaintenanceController::class, 'index'])->name('portal.maintenance.index');
        Route::get('/resident/maintenance/{maintenanceRequest}', [ResidentMaintenanceController::class, 'show'])->name('portal.maintenance.show');
        Route::post('/resident/maintenance', [MaintenanceController::class, 'storeRequest'])->name('portal.maintenance.store');
        Route::put('/resident/maintenance/{maintenanceRequest}', [MaintenanceRequestActionController::class, 'update'])->name('portal.maintenance.update');
        Route::post('/resident/maintenance/{maintenanceRequest}/transition', [MaintenanceRequestActionController::class, 'transition'])->name('portal.maintenance.transition');
        Route::post('/resident/maintenance/{maintenanceRequest}/updates', [MaintenanceRequestActionController::class, 'updateNote'])->name('portal.maintenance.updates.store');
        Route::get('/resident/documents', [ResidentPortalController::class, 'documents'])->name('portal.documents');
        Route::get('/resident/announcements', [ResidentPortalController::class, 'announcements'])->name('portal.announcements');
        Route::get('/expenses', ExpenseDashboardController::class)->middleware('tenant.permission:view_expenses')->name('expenses.index');
        Route::get('/expenses/search', [SupplierInvoiceController::class, 'search'])->middleware('tenant.permission:view_expenses')->name('expenses.search');
        Route::get('/suppliers', [SupplierController::class, 'index'])->middleware('tenant.permission:view_expenses')->name('suppliers.index');
        Route::get('/suppliers/create', [SupplierController::class, 'create'])->middleware('tenant.permission:manage_suppliers')->name('suppliers.create');
        Route::get('/suppliers/search', [SupplierController::class, 'search'])->middleware('tenant.permission:view_expenses')->name('suppliers.search');
        Route::get('/suppliers/{supplier}/edit', [SupplierController::class, 'edit'])->middleware('tenant.permission:manage_suppliers')->name('suppliers.edit');
        Route::get('/suppliers/{supplier}', [SupplierController::class, 'show'])->middleware('tenant.permission:view_expenses')->name('suppliers.show');
        Route::middleware('tenant.permission:manage_suppliers')->group(function () {
            Route::post('/suppliers', [SupplierController::class, 'store'])->name('suppliers.store');
            Route::put('/suppliers/{supplier}', [SupplierController::class, 'update'])->name('suppliers.update');
        });
        Route::get('/expense-categories', [ExpenseCategoryController::class, 'index'])->middleware('tenant.permission:view_expenses')->name('expense-categories.index');
        Route::post('/expense-categories', [ExpenseCategoryController::class, 'store'])->middleware('tenant.permission:create_expenses')->name('expense-categories.store');
        Route::post('/expense-categories/seed', [ExpenseCategoryController::class, 'seed'])->middleware('tenant.permission:create_expenses')->name('expense-categories.seed');
        Route::get('/supplier-contracts', [SupplierContractController::class, 'index'])->middleware('tenant.permission:view_expenses')->name('supplier-contracts.index');
        Route::get('/supplier-contracts/create', [SupplierContractController::class, 'create'])->middleware('tenant.permission:manage_supplier_contracts')->name('supplier-contracts.create');
        Route::get('/supplier-contracts/{contract}', [SupplierContractController::class, 'show'])->middleware('tenant.permission:view_expenses')->name('supplier-contracts.show');
        Route::post('/supplier-contracts', [SupplierContractController::class, 'store'])->middleware('tenant.permission:manage_supplier_contracts')->name('supplier-contracts.store');
        Route::post('/supplier-contracts/{contract}/transition', [SupplierContractController::class, 'transition'])->middleware('tenant.permission:manage_supplier_contracts')->name('supplier-contracts.transition');
        Route::post('/supplier-contracts/{contract}/attachments', [SupplierContractAttachmentController::class, 'store'])->middleware('tenant.permission:manage_supplier_contracts')->name('supplier-contracts.attachments.store');
        Route::get('/supplier-contract-attachments/{attachment}', [SupplierContractAttachmentController::class, 'download'])->middleware('tenant.permission:view_expenses')->name('supplier-contracts.attachments.download');
        Route::delete('/supplier-contract-attachments/{attachment}', [SupplierContractAttachmentController::class, 'destroy'])->middleware('tenant.permission:manage_supplier_contracts')->name('supplier-contracts.attachments.destroy');
        Route::get('/expense-commitments', [ExpenseCommitmentController::class, 'index'])->middleware('tenant.permission:view_expenses')->name('expense-commitments.index');
        Route::get('/expense-commitments/create', [ExpenseCommitmentController::class, 'create'])->middleware('tenant.permission:create_expenses')->name('expense-commitments.create');
        Route::get('/expense-commitments/{commitment}', [ExpenseCommitmentController::class, 'show'])->middleware('tenant.permission:view_expenses')->name('expense-commitments.show');
        Route::post('/expense-commitments', [ExpenseCommitmentController::class, 'store'])->middleware('tenant.permission:create_expenses')->name('expense-commitments.store');
        Route::post('/expense-commitments/{commitment}/transition', [ExpenseCommitmentController::class, 'transition'])->middleware('tenant.permission:approve_commitments')->name('expense-commitments.transition');
        Route::get('/supplier-invoices', [SupplierInvoiceController::class, 'index'])->middleware('tenant.permission:view_expenses')->name('supplier-invoices.index');
        Route::get('/supplier-invoices/create', [SupplierInvoiceController::class, 'create'])->middleware('tenant.permission:create_expenses')->name('supplier-invoices.create');
        Route::get('/supplier-invoices/search', [SupplierInvoiceController::class, 'search'])->middleware('tenant.permission:view_expenses')->name('supplier-invoices.search');
        Route::get('/supplier-invoices/{invoice}', [SupplierInvoiceController::class, 'show'])->middleware('tenant.permission:view_expenses')->name('supplier-invoices.show');
        Route::post('/supplier-invoices', [SupplierInvoiceController::class, 'store'])->middleware('tenant.permission:create_expenses')->name('supplier-invoices.store');
        Route::post('/supplier-invoices/{invoice}/validate', [SupplierInvoiceController::class, 'validateInvoice'])->middleware('tenant.permission:validate_expenses')->name('supplier-invoices.validate');
        Route::post('/supplier-invoices/{invoice}/cancel', [SupplierInvoiceController::class, 'cancel'])->middleware('tenant.permission:cancel_expenses')->name('supplier-invoices.cancel');
        Route::post('/supplier-invoices/{invoice}/attachments', [SupplierInvoiceController::class, 'attach'])->middleware('tenant.permission:create_expenses')->name('supplier-invoices.attachments.store');
        Route::get('/supplier-invoice-attachments/{attachment}', [SupplierInvoiceController::class, 'download'])->middleware('tenant.permission:view_expenses')->name('supplier-invoices.attachments.download');
        Route::get('/supplier-settlements', [SupplierSettlementController::class, 'index'])->middleware('tenant.permission:view_supplier_payables')->name('supplier-settlements.index');
        Route::get('/supplier-settlements/create', [SupplierSettlementController::class, 'create'])->middleware('tenant.permission:create_settlements')->name('supplier-settlements.create');
        Route::get('/supplier-settlements/{settlement}', [SupplierSettlementController::class, 'show'])->middleware('tenant.permission:view_supplier_payables')->name('supplier-settlements.show');
        Route::post('/supplier-settlements', [SupplierSettlementController::class, 'store'])->middleware('tenant.permission:create_settlements')->name('supplier-settlements.store');
        Route::post('/supplier-settlements/{settlement}/validate', [SupplierSettlementController::class, 'validateSettlement'])->middleware('tenant.permission:validate_settlements')->name('supplier-settlements.validate');
        Route::post('/supplier-settlements/{settlement}/reverse', [SupplierSettlementController::class, 'reverse'])->middleware('tenant.permission:reverse_settlements')->name('supplier-settlements.reverse');
        Route::post('/supplier-settlements/{settlement}/voucher/retry', [SupplierSettlementController::class, 'retryVoucher'])->middleware('tenant.permission:validate_settlements')->name('supplier-settlements.voucher.retry');
        Route::get('/expenses/vouchers/{document}', [FinancialDocumentController::class, 'download'])->middleware('tenant.permission:view_supplier_payables')->name('supplier-vouchers.download');
        Route::get('/supplier-credit-notes', [SupplierCreditNoteController::class, 'index'])->middleware('tenant.permission:view_expenses')->name('supplier-credit-notes.index');
        Route::get('/supplier-credit-notes/create', [SupplierCreditNoteController::class, 'create'])->middleware('tenant.permission:manage_credit_notes')->name('supplier-credit-notes.create');
        Route::get('/supplier-credit-notes/{credit}', [SupplierCreditNoteController::class, 'show'])->middleware('tenant.permission:view_expenses')->name('supplier-credit-notes.show');
        Route::post('/supplier-credit-notes', [SupplierCreditNoteController::class, 'store'])->middleware('tenant.permission:manage_credit_notes')->name('supplier-credit-notes.store');
        Route::post('/supplier-credit-notes/{credit}/validate', [SupplierCreditNoteController::class, 'validateCredit'])->middleware('tenant.permission:manage_credit_notes')->name('supplier-credit-notes.validate');
        Route::post('/supplier-credit-notes/{credit}/cancel', [SupplierCreditNoteController::class, 'cancel'])->middleware('tenant.permission:manage_credit_notes')->name('supplier-credit-notes.cancel');
        Route::get('/supplier-payables', SupplierPayableController::class)->middleware('tenant.permission:view_supplier_payables')->name('supplier-payables.index');
        Route::get('/expenses/suppliers/{supplier}/statement', [SupplierStatementController::class, 'show'])->middleware('tenant.permission:view_supplier_payables')->name('suppliers.statement');
        Route::get('/budgets', [BudgetController::class, 'index'])->middleware('tenant.permission:view_expenses')->name('budgets.index');
        Route::get('/budgets/create', [BudgetController::class, 'create'])->middleware('tenant.permission:manage_budgets')->name('budgets.create');
        Route::get('/budgets/{budget}', [BudgetController::class, 'show'])->middleware('tenant.permission:view_expenses')->name('budgets.show');
        Route::post('/budgets', [BudgetController::class, 'store'])->middleware('tenant.permission:manage_budgets')->name('budgets.store');
        Route::post('/budgets/{budget}/approve', [BudgetController::class, 'approve'])->middleware('tenant.permission:approve_budgets')->name('budgets.approve');
        Route::post('/budgets/{budget}/revise', [BudgetController::class, 'revise'])->middleware('tenant.permission:manage_budgets')->name('budgets.revise');
        Route::post('/budgets/{budget}/lock', [BudgetController::class, 'lock'])->middleware('tenant.permission:approve_budgets')->name('budgets.lock');
        Route::post('/budgets/{budget}/unlock', [BudgetController::class, 'unlock'])->middleware('tenant.permission:approve_budgets')->name('budgets.unlock');
        Route::post('/budgets/{budget}/archive', [BudgetController::class, 'archive'])->middleware('tenant.permission:approve_budgets')->name('budgets.archive');
        Route::post('/budgets/{budget}/prepare-fund-call', [BudgetController::class, 'prepareFundCall'])->middleware('tenant.permission:manage_budgets')->name('budgets.prepare-fund-call');
        Route::redirect('/expenses/suppliers', '/suppliers');
        Route::redirect('/expenses/contracts', '/supplier-contracts');
        Route::redirect('/expenses/commitments', '/expense-commitments');
        Route::redirect('/expenses/invoices', '/supplier-invoices');
        Route::redirect('/expenses/settlements', '/supplier-settlements');
        Route::redirect('/expenses/credit-notes', '/supplier-credit-notes');
        Route::redirect('/expenses/payables', '/supplier-payables');
        Route::redirect('/expenses/budgets', '/budgets');
        Route::redirect('/expenses/categories', '/expense-categories');
        Route::get('/documents', [ResidenceDocumentController::class, 'index'])->middleware('tenant.permission:view_documents')->name('documents.index');
        Route::post('/documents', [ResidenceDocumentController::class, 'store'])->middleware('tenant.permission:manage_documents')->name('documents.store');
        Route::post('/documents/{document}/versions', [ResidenceDocumentController::class, 'version'])->middleware('tenant.permission:manage_documents')->name('documents.versions.store');
        Route::post('/documents/{document}/transition', [ResidenceDocumentController::class, 'transition'])->middleware('tenant.permission:publish_documents')->name('documents.transition');
        Route::post('/documents/{document}/retry', [ResidenceDocumentController::class, 'retry'])->middleware('tenant.permission:publish_documents')->name('documents.retry');
        Route::get('/documents/versions/{version}/download', [ResidenceDocumentController::class, 'download'])->name('documents.download');
        Route::get('/announcements', [AnnouncementController::class, 'index'])->middleware('tenant.permission:view_announcements')->name('announcements.index');
        Route::post('/announcements', [AnnouncementController::class, 'store'])->middleware('tenant.permission:manage_announcements')->name('announcements.store');
        Route::post('/announcements/{announcement}/publish', [AnnouncementController::class, 'publish'])->middleware('tenant.permission:publish_announcements')->name('announcements.publish');
        Route::post('/announcements/{announcement}/retry', [AnnouncementController::class, 'retry'])->middleware('tenant.permission:publish_announcements')->name('announcements.retry');
        Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
        Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
        Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
        Route::put('/notifications/preferences', [NotificationController::class, 'preferences'])->name('notifications.preferences');

        Route::get('/maintenance', [MaintenanceController::class, 'dashboard'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.dashboard');
        Route::get('/maintenance/requests', [MaintenanceController::class, 'requests'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.requests.index');
        Route::get('/maintenance/requests/create', [MaintenanceController::class, 'createRequest'])->middleware('tenant.permission:create_maintenance_requests')->name('maintenance.requests.create');
        Route::post('/maintenance/requests', [MaintenanceController::class, 'storeRequest'])->middleware('tenant.permission:create_maintenance_requests')->name('maintenance.requests.store');
        Route::get('/maintenance/requests/{maintenanceRequest}/edit', [MaintenanceController::class, 'editRequest'])->middleware('tenant.permission:manage_maintenance_requests')->name('maintenance.requests.edit');
        Route::get('/maintenance/requests/{maintenanceRequest}', [MaintenanceController::class, 'showRequest'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.requests.show');
        Route::put('/maintenance/requests/{maintenanceRequest}', [MaintenanceRequestActionController::class, 'update'])->middleware('tenant.permission:manage_maintenance_requests')->name('maintenance.requests.update');
        Route::post('/maintenance/requests/{maintenanceRequest}/transition', [MaintenanceRequestActionController::class, 'transition'])->middleware('tenant.permission:transition_maintenance_requests')->name('maintenance.requests.transition');
        Route::post('/maintenance/requests/{maintenanceRequest}/assign', [MaintenanceRequestActionController::class, 'assign'])->middleware('tenant.permission:assign_maintenance_requests')->name('maintenance.requests.assign');
        Route::post('/maintenance/requests/{maintenanceRequest}/updates', [MaintenanceRequestActionController::class, 'updateNote'])->middleware('tenant.permission:manage_maintenance_requests')->name('maintenance.requests.updates.store');
        Route::get('/maintenance/categories', [MaintenanceController::class, 'categories'])->middleware('tenant.permission:manage_maintenance_categories')->name('maintenance.categories.index');
        Route::post('/maintenance/categories', [MaintenanceController::class, 'storeCategory'])->middleware('tenant.permission:manage_maintenance_categories')->name('maintenance.categories.store');
        Route::post('/maintenance/categories/seed', [MaintenanceController::class, 'seedCategories'])->middleware('tenant.permission:manage_maintenance_categories')->name('maintenance.categories.seed');
        Route::put('/maintenance/categories/{category}', [MaintenanceController::class, 'updateCategory'])->middleware('tenant.permission:manage_maintenance_categories')->name('maintenance.categories.update');
        Route::get('/maintenance/equipment', [MaintenanceController::class, 'equipment'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.equipment.index');
        Route::post('/maintenance/equipment', [MaintenanceController::class, 'storeEquipment'])->middleware('tenant.permission:manage_maintenance_equipment')->name('maintenance.equipment.store');
        Route::get('/maintenance/equipment/{equipment}', [MaintenanceController::class, 'showEquipment'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.equipment.show');
        Route::put('/maintenance/equipment/{equipment}', [MaintenanceController::class, 'updateEquipment'])->middleware('tenant.permission:manage_maintenance_equipment')->name('maintenance.equipment.update');
        Route::post('/maintenance/equipment/{equipment}/transition', [MaintenanceController::class, 'equipmentTransition'])->middleware('tenant.permission:manage_maintenance_equipment')->name('maintenance.equipment.transition');
        Route::post('/maintenance/requests/{maintenanceRequest}/quotations', [MaintenanceQuotationController::class, 'store'])->middleware('tenant.permission:manage_maintenance_quotations')->name('maintenance.quotations.store');
        Route::post('/maintenance/quotations/{quotation}/accept', [MaintenanceQuotationController::class, 'accept'])->middleware('tenant.permission:accept_maintenance_quotations')->name('maintenance.quotations.accept');
        Route::post('/maintenance/quotations/{quotation}/replace', [MaintenanceQuotationController::class, 'replace'])->middleware('tenant.permission:accept_maintenance_quotations')->name('maintenance.quotations.replace');
        Route::get('/maintenance/work-orders', [MaintenanceWorkOrderController::class, 'index'])->middleware('tenant.permission:view_work_orders')->name('maintenance.work-orders.index');
        Route::post('/maintenance/work-orders', [MaintenanceWorkOrderController::class, 'store'])->middleware('tenant.permission:manage_work_orders')->name('maintenance.work-orders.store');
        Route::post('/maintenance/work-orders/{workOrder}/transition', [MaintenanceWorkOrderController::class, 'transition'])->middleware('tenant.permission:view_work_orders')->name('maintenance.work-orders.transition');
        Route::put('/maintenance/work-orders/{workOrder}/schedule', [MaintenanceWorkOrderController::class, 'reschedule'])->middleware('tenant.permission:manage_work_orders')->name('maintenance.work-orders.schedule');
        Route::post('/maintenance/work-orders/{workOrder}/invoice', [MaintenanceWorkOrderController::class, 'createInvoice'])->middleware('tenant.permission:create_work_order_invoices')->name('maintenance.work-orders.invoice.store');
        Route::post('/maintenance/work-orders/{workOrder}/invoice/link', [MaintenanceWorkOrderController::class, 'linkInvoice'])->middleware('tenant.permission:create_work_order_invoices')->name('maintenance.work-orders.invoice.link');
        Route::get('/maintenance/preventive', [PreventiveMaintenanceController::class, 'index'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.preventive.index');
        Route::post('/maintenance/preventive', [PreventiveMaintenanceController::class, 'store'])->middleware('tenant.permission:manage_preventive_plans')->name('maintenance.preventive.store');
        Route::put('/maintenance/preventive/{plan}', [PreventiveMaintenanceController::class, 'update'])->middleware('tenant.permission:manage_preventive_plans')->name('maintenance.preventive.update');
        Route::get('/maintenance/kanban', [MaintenanceController::class, 'operations'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.operations.kanban');
        Route::get('/maintenance/calendar', [MaintenanceController::class, 'operations'])->middleware('tenant.permission:view_maintenance_requests')->name('maintenance.operations.calendar');
        Route::get('/maintenance/overdue', [MaintenanceController::class, 'operations'])->middleware('tenant.permission:view_maintenance_reports')->name('maintenance.operations.overdue');
        Route::get('/maintenance/supplier-performance', [MaintenanceController::class, 'operations'])->middleware('tenant.permission:view_maintenance_reports')->name('maintenance.operations.suppliers');
        Route::get('/maintenance/reports', [MaintenanceController::class, 'operations'])->middleware('tenant.permission:view_maintenance_reports')->name('maintenance.operations.reports');
        Route::post('/maintenance/attachments/{type}/{id}', [MaintenanceAttachmentController::class, 'store'])->name('maintenance.attachments.store');
        Route::get('/maintenance/attachments/{attachment}', [MaintenanceAttachmentController::class, 'download'])->name('maintenance.attachments.download');

        Route::get('/governance', [GovernanceController::class, 'dashboard'])->middleware('tenant.permission:view_governance_dashboard')->name('governance.dashboard');
        Route::get('/governance/assemblies', [GovernanceController::class, 'index'])->middleware('tenant.permission:view_assemblies')->name('governance.index');
        Route::get('/governance/assemblies/create', [GovernanceController::class, 'create'])->middleware('tenant.permission:create_assemblies')->name('governance.create');
        Route::post('/governance/assemblies', [GovernanceController::class, 'store'])->middleware('tenant.permission:create_assemblies')->name('governance.store');
        Route::get('/governance/assemblies/{assembly}', [GovernanceController::class, 'show'])->middleware('tenant.permission:view_assemblies')->name('governance.show');
        Route::post('/governance/assemblies/{assembly}/agenda', [GovernanceController::class, 'addAgenda'])->middleware('tenant.permission:manage_agenda')->name('governance.agenda.store');
        Route::post('/governance/agenda-items/{item}/amend', [GovernanceActionController::class, 'amendAgenda'])->middleware('tenant.permission:manage_agenda')->name('governance.agenda.amend');
        Route::post('/governance/assemblies/{a}/freeze', [GovernanceActionController::class, 'freeze'])->middleware('tenant.permission:manage_electorate_snapshots')->name('governance.freeze');
        Route::post('/governance/assemblies/{a}/issue', [GovernanceActionController::class, 'issue'])->middleware('tenant.permission:issue_convocations')->name('governance.issue');
        Route::post('/governance/assemblies/{a}/transition', [GovernanceActionController::class, 'transition'])->middleware('tenant.permission:transition_assemblies')->name('governance.transition');
        Route::put('/governance/assemblies/{a}/officers', [GovernanceActionController::class, 'officers'])->middleware('tenant.permission:manage_assemblies')->name('governance.officers');
        Route::post('/governance/assemblies/{a}/second-convocation', [GovernanceActionController::class, 'second'])->middleware('tenant.permission:issue_convocations')->name('governance.second');
        Route::post('/governance/assemblies/{a}/attendance/{e}', [GovernanceActionController::class, 'attendance'])->middleware('tenant.permission:record_attendance')->name('governance.attendance');
        Route::post('/governance/electorate/{e}/correct', [GovernanceActionController::class, 'correctElectorate'])->middleware('tenant.permission:manage_electorate_snapshots')->name('governance.electorate.correct');
        Route::post('/governance/assemblies/{a}/quorum', [GovernanceActionController::class, 'quorum'])->middleware('tenant.permission:record_attendance')->name('governance.quorum');
        Route::post('/governance/convocation-recipients/{recipient}/delivery', [GovernanceActionController::class, 'delivery'])->middleware('tenant.permission:issue_convocations')->name('governance.delivery');
        Route::post('/governance/proxies/{proxy}/verify', [GovernanceActionController::class, 'verifyProxy'])->middleware('tenant.permission:verify_proxies')->name('governance.proxies.verify');
        Route::post('/governance/proxies/{proxy}/revoke', [GovernanceActionController::class, 'revokeProxy'])->middleware('tenant.permission:verify_proxies')->name('governance.proxies.revoke');
        Route::post('/governance/resolutions/{resolution}/ballots', [GovernanceActionController::class, 'ballot'])->middleware('tenant.permission:record_ballots')->name('governance.ballots.store');
        Route::put('/governance/ballots/{ballot}', [GovernanceActionController::class, 'correctBallot'])->middleware('tenant.permission:correct_ballots')->name('governance.ballots.correct');
        Route::post('/governance/resolutions/{resolution}/finalize', [GovernanceActionController::class, 'finalize'])->middleware('tenant.permission:finalize_results')->name('governance.results.finalize');
        Route::post('/governance/resolutions/{resolution}/reopen', [GovernanceActionController::class, 'reopenResult'])->middleware('tenant.permission:reopen_results')->name('governance.results.reopen');
        Route::post('/governance/assemblies/{a}/minutes', [GovernanceActionController::class, 'prepareMinutes'])->middleware('tenant.permission:prepare_minutes')->name('governance.minutes.prepare');
        Route::post('/governance/minute-versions/{version}/review', [GovernanceActionController::class, 'reviewMinutes'])->middleware('tenant.permission:prepare_minutes')->name('governance.minutes.review');
        Route::post('/governance/minutes/{minutes}/sign', [GovernanceActionController::class, 'signMinutes'])->middleware('tenant.permission:sign_minutes')->name('governance.minutes.sign');
        Route::post('/governance/minutes/{minutes}/corrective-annex', [GovernanceActionController::class, 'correctiveAnnex'])->middleware('tenant.permission:sign_minutes')->name('governance.minutes.corrective-annex');
        Route::post('/governance/assemblies/{a}/decision-notifications', [GovernanceActionController::class, 'prepareNotifications'])->middleware('tenant.permission:manage_decision_notifications')->name('governance.decisions.prepare');
        Route::post('/governance/decision-notifications/{notification}/deliver', [GovernanceActionController::class, 'deliverDecision'])->middleware('tenant.permission:manage_decision_notifications')->name('governance.decisions.deliver');
        Route::post('/governance/resolutions/{resolution}/execution-actions', [GovernanceActionController::class, 'execution'])->middleware('tenant.permission:manage_execution_actions')->name('governance.execution.store');
        Route::post('/governance/execution-actions/{action}/fund-call', [GovernanceActionController::class, 'fundCall'])->middleware('tenant.permission:manage_execution_actions')->name('governance.execution.fund-call');
        Route::post('/governance/execution-actions/{action}/maintenance-request', [GovernanceActionController::class, 'maintenanceRequest'])->middleware('tenant.permission:manage_execution_actions')->name('governance.execution.maintenance-request');
        Route::post('/governance/execution-actions/{action}/complete', [GovernanceActionController::class, 'completeExecution'])->middleware('tenant.permission:manage_execution_actions')->name('governance.execution.complete');
        Route::post('/governance/agenda-questions/{question}/decide', [GovernanceActionController::class, 'decideQuestion'])->middleware('tenant.permission:manage_agenda')->name('governance.questions.decide');
        Route::post('/governance/assemblies/{a}/documents', [GovernanceDocumentController::class, 'store'])->middleware('tenant.permission:manage_governance_document_room')->name('governance.documents.store');
        Route::post('/governance/documents/{document}/versions', [GovernanceDocumentController::class, 'version'])->middleware('tenant.permission:manage_governance_document_room')->name('governance.documents.version');
        Route::post('/governance/documents/{document}/versions/{version}/publish', [GovernanceDocumentController::class, 'publish'])->middleware('tenant.permission:manage_governance_document_room')->name('governance.documents.publish');
        Route::post('/governance/documents/{document}/archive', [GovernanceDocumentController::class, 'archive'])->middleware('tenant.permission:manage_governance_document_room')->name('governance.documents.archive');
        Route::get('/governance/document-versions/{version}/download', [GovernanceDocumentController::class, 'download'])->name('governance.documents.download');
        Route::get('/governance/convocations/{convocation}/download', [GovernanceDocumentController::class, 'convocation'])->middleware('tenant.permission:view_assemblies')->name('governance.convocations.download');
        Route::get('/governance/minutes/{version}/download', [GovernanceDocumentController::class, 'minutes'])->middleware('tenant.permission:view_assemblies')->name('governance.minutes.download');
        Route::get('/governance/mandates', [GovernanceMandateController::class, 'index'])->middleware('tenant.permission:manage_governance_mandates')->name('governance.mandates.index');
        Route::post('/governance/mandates', [GovernanceMandateController::class, 'store'])->middleware('tenant.permission:manage_governance_mandates')->name('governance.mandates.store');
        Route::post('/governance/mandates/{mandate}/transition', [GovernanceMandateController::class, 'transition'])->middleware('tenant.permission:manage_governance_mandates')->name('governance.mandates.transition');
        Route::get('/governance/reports', [GovernanceController::class, 'dashboard'])->middleware('tenant.permission:view_governance_reports')->name('governance.reports');

        Route::get('/resident/governance', [OwnerGovernanceController::class, 'index'])->name('owner-governance.index');
        Route::get('/resident/governance/convocations/{convocation}/download', [OwnerGovernanceController::class, 'convocation'])->name('owner-governance.convocations.download');
        Route::get('/resident/governance/minutes/{version}/download', [OwnerGovernanceController::class, 'minutes'])->name('owner-governance.minutes.download');
        Route::get('/resident/governance/{a}/proxy-form', [OwnerGovernanceController::class, 'proxyForm'])->name('owner-governance.proxy-form');
        Route::get('/resident/governance/{a}', [OwnerGovernanceController::class, 'show'])->name('owner-governance.show');
        Route::post('/resident/governance/{a}/questions', [OwnerGovernanceController::class, 'question'])->name('owner-governance.questions.store');
        Route::post('/resident/governance/{a}/proxies', [OwnerGovernanceController::class, 'proxy'])->name('owner-governance.proxies.store');
        Route::middleware('tenant.permission:manage_team')->group(function () {
            Route::get('/team', [TeamController::class, 'index'])->name('team.index');
            Route::post('/team/invitations', [TeamController::class, 'invite'])->name('team.invite');
            Route::post('/team/invitations/{invitation}/cancel', [TeamController::class, 'cancel'])->name('team.cancel');
            Route::post('/team/invitations/{invitation}/resend', [TeamController::class, 'resend'])->name('team.resend');
            Route::put('/team/members/{user}/role', [TeamController::class, 'role'])->name('team.role');
        });
    });
});

require __DIR__.'/auth.php';
