<?php

$section = fn (string $id, string $heading, string $body, array $items = []) => compact('id', 'heading', 'body', 'items');
$language = fn (string $title, string $summary, array $sections) => compact('title', 'summary', 'sections');
$article = function (
    string $category,
    int $order,
    array $fr,
    array $ar,
    ?string $permission = null,
    array $routes = [],
    array $keywords = [],
    array $keywordsAr = [],
    array $related = [],
    array $roles = [],
    int $minutes = 6,
) {
    return [
        'category' => $category,
        'order' => $order,
        'permission' => $permission,
        'routes' => $routes,
        'keywords' => $keywords,
        'keywords_ar' => $keywordsAr,
        'related' => $related,
        'roles' => $roles,
        'reading_minutes' => $minutes,
        'fr' => $fr,
        'ar' => $ar,
    ];
};

$module = function (
    string $category,
    int $order,
    string $titleFr,
    string $titleAr,
    string $purposeFr,
    string $purposeAr,
    string $accessFr,
    string $accessAr,
    string $workflowFr,
    string $workflowAr,
    string $controlsFr,
    string $controlsAr,
    ?string $permission,
    array $routes,
    array $keywords = [],
    array $keywordsAr = [],
    array $related = [],
    array $roles = [],
) use ($article, $language, $section) {
    return $article(
        $category,
        $order,
        $language($titleFr, $purposeFr, [
            $section('purpose', 'Rôle et relations', $purposeFr),
            $section('access', 'Accès et prérequis', $accessFr),
            $section('procedure', 'Procédure habituelle', $workflowFr),
            $section('controls', 'Statuts, contrôles et correction', $controlsFr),
        ]),
        $language($titleAr, $purposeAr, [
            $section('purpose', 'الغرض والعلاقات', $purposeAr),
            $section('access', 'الصلاحيات والمتطلبات', $accessAr),
            $section('procedure', 'المسار المعتاد', $workflowAr),
            $section('controls', 'الحالات والضوابط والتصحيح', $controlsAr),
        ]),
        $permission,
        $routes,
        $keywords,
        $keywordsAr,
        $related,
        $roles,
    );
};

$check = function (
    string $articleId,
    string $titleFr,
    string $titleAr,
    string $purposeFr,
    string $purposeAr,
    string $whoFr,
    string $whoAr,
    string $pathFr,
    string $pathAr,
    string $fieldsFr,
    string $fieldsAr,
    array $actionsFr,
    array $actionsAr,
    string $prerequisitesFr,
    string $prerequisitesAr,
    string $resultFr,
    string $resultAr,
    string $mistakesFr,
    string $mistakesAr,
    string $unlocksFr,
    string $unlocksAr,
) {
    return [
        'article_id' => $articleId,
        'fr' => ['title' => $titleFr, 'purpose' => $purposeFr, 'who' => $whoFr, 'path' => $pathFr, 'fields' => $fieldsFr, 'actions' => $actionsFr, 'prerequisites' => $prerequisitesFr, 'result' => $resultFr, 'mistakes' => $mistakesFr, 'unlocks' => $unlocksFr],
        'ar' => ['title' => $titleAr, 'purpose' => $purposeAr, 'who' => $whoAr, 'path' => $pathAr, 'fields' => $fieldsAr, 'actions' => $actionsAr, 'prerequisites' => $prerequisitesAr, 'result' => $resultAr, 'mistakes' => $mistakesAr, 'unlocks' => $unlocksAr],
    ];
};

return [
    'updated_at' => '2026-07-27',
    'categories' => [
        'start' => ['order' => 10, 'fr' => 'Bien démarrer', 'ar' => 'البدء'],
        'workflows' => ['order' => 20, 'fr' => 'Parcours complets', 'ar' => 'مسارات العمل'],
        'modules' => ['order' => 30, 'fr' => 'Modules et données', 'ar' => 'الوحدات والبيانات'],
        'roles' => ['order' => 40, 'fr' => 'Guides par rôle', 'ar' => 'أدلة حسب الدور'],
        'faq' => ['order' => 50, 'fr' => 'Questions fréquentes', 'ar' => 'الأسئلة الشائعة'],
        'glossary' => ['order' => 60, 'fr' => 'Glossaire', 'ar' => 'المصطلحات'],
    ],
    'articles' => [
        'getting-started' => $article(
            'start', 10,
            $language('Découvrir EvoSyndic', 'Comprendre le contexte organisation/résidence et l’ordre sûr de mise en service.', [
                $section('context', 'Toujours vérifier le contexte', 'Le sélecteur supérieur fixe l’organisation et la résidence actives. Les écrans, écritures et documents utilisent ce contexte. Avant toute saisie, vérifiez les deux noms.'),
                $section('order', 'Ordre recommandé', 'Créez la résidence et sa structure, rattachez les contacts, définissez propriété et occupation, puis configurez répartitions et finance avant les opérations.', ['Ne validez pas un appel de fonds avant de contrôler les tantièmes.', 'Ne supprimez pas une preuve financière validée : utilisez l’annulation ou l’extourne prévue.']),
                $section('language', 'Langue et sécurité', 'La langue se règle dans le profil. Le français et l’arabe s’affichent séparément. Chaque utilisateur ne voit que les résidences et modules autorisés.'),
            ]),
            $language('التعرّف على EvoSyndic', 'فهم سياق المؤسسة والإقامة وترتيب الإعداد الآمن.', [
                $section('context', 'تحقق دائما من السياق', 'يحدد المنتقي العلوي المؤسسة والإقامة النشطتين. تعتمد الشاشات والقيود والمستندات على هذا السياق، لذلك تحقق من الاسمين قبل الإدخال.'),
                $section('order', 'الترتيب الموصى به', 'أنشئ الإقامة وهيكلها، واربط جهات الاتصال بالملكية والإشغال، ثم اضبط مفاتيح التوزيع والمالية قبل العمليات.', ['لا تعتمد نداء أموال قبل التحقق من الحصص.', 'لا تحذف دليلا ماليا معتمدا؛ استعمل الإلغاء أو القيد العكسي المتاح.']),
                $section('language', 'اللغة والأمان', 'تُضبط اللغة من الملف الشخصي. تظهر كل لغة منفصلة، ولا يرى المستخدم إلا الإقامات والوحدات المسموح بها.'),
            ]),
            null, ['dashboard'], ['démarrage', 'contexte', 'première utilisation'], ['البدء', 'السياق', 'أول استعمال'], ['first-use-checklist'], [], 4,
        ),
        'first-use-checklist' => $article(
            'start', 20,
            $language('Liste de première utilisation', 'Une liste reprise automatiquement quand les données permettent une vérification fiable.', [
                $section('how', 'Comment la progression fonctionne', 'Les étapes structurelles sont terminées uniquement quand la donnée existe dans l’organisation active. Les étapes d’information peuvent être cochées manuellement. Ouvrir un article ne termine jamais une étape.'),
                $section('restart', 'Reprendre ou recommencer', 'Vous pouvez revenir à toute étape. Réinitialiser efface seulement les coches manuelles de votre compte dans cette organisation; aucune donnée métier n’est modifiée.'),
            ]),
            $language('قائمة الاستعمال الأول', 'قائمة تتحقق تلقائيا عندما تسمح البيانات بقياس موثوق.', [
                $section('how', 'طريقة احتساب التقدم', 'لا تكتمل الخطوات الهيكلية إلا بوجود البيانات داخل المؤسسة النشطة. يمكن تعليم الخطوات الإرشادية يدويا. فتح المقال لا يُكمل أي خطوة.'),
                $section('restart', 'المتابعة أو إعادة البدء', 'يمكن الرجوع إلى أي خطوة. إعادة الضبط تمسح العلامات اليدوية لحسابك داخل هذه المؤسسة فقط ولا تغيّر بيانات العمل.'),
            ]),
            null, [], ['checklist', 'configuration', 'onboarding'], ['قائمة', 'إعداد', 'تهيئة'], ['getting-started'],
        ),
        'residence-setup-workflow' => $module(
            'workflows', 10, 'Créer et configurer une résidence', 'إنشاء إقامة وضبطها',
            'Une résidence est le périmètre opérationnel qui regroupe bâtiments, lots, comptes, exercices et documents.',
            'الإقامة هي النطاق التشغيلي الذي يجمع المباني والوحدات والحسابات والسنوات والمستندات.',
            'Les permissions « voir », « créer » et « modifier les résidences » sont distinctes. Une organisation active est obligatoire.',
            'صلاحيات عرض الإقامات وإنشائها وتعديلها منفصلة، ويلزم اختيار مؤسسة نشطة.',
            'Ouvrez Résidences > Ajouter. Renseignez identité, adresse et paramètres. Enregistrez, sélectionnez la résidence, puis créez sa structure. Le résultat attendu est une résidence au statut configuration, prête à recevoir ses lots.',
            'افتح الإقامات ثم إضافة. أدخل الهوية والعنوان والإعدادات واحفظ، ثم اختر الإقامة وأنشئ هيكلها. النتيجة إقامة في طور الإعداد جاهزة للوحدات.',
            'L’archivage masque la résidence sans supprimer son historique. Une résidence ne devient opérationnelle que lorsque les propriétaires et répartitions requis sont présents. Corrigez les données manquantes avant activation.',
            'تخفي الأرشفة الإقامة دون حذف سجلها. لا تصبح تشغيلية إلا بعد استكمال الملاك ومفاتيح التوزيع المطلوبة. صحح النواقص قبل التفعيل.',
            'view_residences', ['residences.index', 'residences.create', 'residences.show', 'residences.edit'], ['résidence', 'immeuble', 'configuration'], ['إقامة', 'عمارة', 'إعداد'], ['property-structure', 'contacts-ownership-occupancy'],
        ),
        'import-workflow' => $module(
            'workflows', 20, 'Importer lots et contacts', 'استيراد الوحدات وجهات الاتصال',
            'L’import traite les lots, contacts, propriétés, occupations et répartitions à partir de CSV ou XLSX.',
            'يعالج الاستيراد الوحدات وجهات الاتصال والملكيات والإشغال والتوزيعات من CSV أو XLSX.',
            'Permission « importer des données », résidence active et fichier de 10 Mo maximum. Téléchargez toujours le modèle du type choisi.',
            'يلزم إذن استيراد البيانات وإقامة نشطة وملف لا يتجاوز 10 ميغابايت. نزّل نموذج النوع المختار.',
            'Imports > choisir le type > téléverser > associer les colonnes > contrôler l’aperçu > confirmer. Traitez les lignes en erreur avant de poursuivre les dépendances.',
            'الاستيراد > اختيار النوع > رفع الملف > مطابقة الأعمدة > مراجعة المعاينة > تأكيد. عالج الأسطر الخاطئة قبل البيانات التابعة.',
            'États: téléversé, association, en attente, terminé, terminé avec erreurs ou échec. Le retour arrière n’est proposé qu’aux lots importés sans dépendances ultérieures.',
            'الحالات: مرفوع، مطابقة، انتظار، مكتمل، مكتمل مع أخطاء أو فشل. التراجع متاح فقط عندما لا توجد بيانات لاحقة تعتمد على المستورد.',
            'import_data', ['imports.index', 'imports.map'], ['import', 'csv', 'xlsx', 'mapping'], ['استيراد', 'مطابقة', 'ملف'], ['property-structure', 'contacts-ownership-occupancy'],
        ),
        'finance-workflow' => $module(
            'workflows', 30, 'Du budget au recouvrement', 'من الميزانية إلى التحصيل',
            'Le cycle relie exercice, budget, catégories de charges, appels de fonds, créances, paiements et affectations.',
            'تربط الدورة السنة المالية والميزانية وفئات المصاريف ونداءات الأموال والمستحقات والدفعات والتخصيصات.',
            'Une résidence, des lots avec propriétaires, des clés de répartition, un exercice et un compte financier sont requis.',
            'يلزم وجود إقامة ووحدات بملاك ومفاتيح توزيع وسنة مالية وحساب مالي.',
            'Préparez l’exercice et le budget, contrôlez les clés, créez puis validez l’appel. Enregistrez le paiement, validez-le, puis affectez son crédit aux créances. Vérifiez l’état de lot et les impayés.',
            'هيئ السنة والميزانية، راجع مفاتيح التوزيع، أنشئ نداء الأموال واعتمده. سجل الدفعة واعتمدها ثم خصص رصيدها للمستحقات، وراجع كشف الوحدة والمتأخرات.',
            'Un brouillon peut être corrigé. Une opération validée se corrige par annulation ou contre-opération. Un crédit est la partie validée non encore affectée; il n’est pas un impayé négatif.',
            'يمكن تصحيح المسودة. تُصحح العملية المعتمدة بالإلغاء أو العملية العكسية. الرصيد الدائن هو الجزء المعتمد غير المخصص وليس متأخرا سالبا.',
            'view_finance', ['finance.index', 'fund-calls.index', 'payments.index', 'finance.outstanding', 'finance.statements'], ['budget', 'appel de fonds', 'paiement', 'crédit', 'impayé'], ['ميزانية', 'نداء أموال', 'دفعة', 'رصيد', 'متأخر'], ['budgets', 'fund-calls', 'payments-credit', 'accounting-reconciliation'],
        ),
        'supplier-workflow' => $module(
            'workflows', 40, 'De la facture fournisseur au règlement', 'من فاتورة المورد إلى التسوية',
            'Le cycle fournisseur distingue engagement, facture, avoir, exigible et règlement.',
            'تميّز دورة المورد بين الالتزام والفاتورة والإشعار الدائن والمبلغ المستحق والتسوية.',
            'Fournisseur actif, exercice ouvert, catégorie de dépense et compte financier selon l’opération.',
            'مورد نشط وسنة مفتوحة وفئة مصروف وحساب مالي حسب العملية.',
            'Créez ou choisissez le fournisseur et le contrat. Saisissez la facture et ses lignes, joignez l’original, validez, puis créez un règlement et affectez-le en FIFO ou manuellement.',
            'أنشئ المورد والعقد أو اخترهما. أدخل الفاتورة وبنودها وأرفق الأصل ثم اعتمدها، وبعدها أنشئ تسوية وخصصها تلقائيا بالأقدم أو يدويا.',
            'La facture validée n’est pas supprimée. Utilisez annulation ou avoir. Le règlement validé est inversé, pas effacé. Les pièces privées restent limitées aux permissions dédiées.',
            'لا تُحذف الفاتورة المعتمدة؛ استعمل الإلغاء أو الإشعار الدائن. تُعكس التسوية المعتمدة ولا تُمحى. المرفقات الخاصة محمية بصلاحياتها.',
            'view_expenses', ['expenses.index', 'supplier-invoices.index', 'supplier-settlements.index', 'supplier-payables.index'], ['fournisseur', 'facture', 'règlement', 'avoir', 'exigible'], ['مورد', 'فاتورة', 'تسوية', 'إشعار دائن', 'مستحق'], ['suppliers-contracts', 'supplier-invoices', 'supplier-settlements'],
        ),
        'maintenance-workflow' => $module(
            'workflows', 50, 'Traiter une demande de maintenance', 'معالجة طلب صيانة',
            'Une demande signale un incident; les devis, ordres de travail, équipements et plans préventifs organisent son traitement.',
            'يسجل الطلب حادثا، بينما تنظم عروض الأسعار وأوامر العمل والمعدات والخطط الوقائية معالجته.',
            'Les résidents peuvent créer et suivre leurs propres demandes. Les équipes autorisées qualifient, affectent et font évoluer le dossier.',
            'يمكن للسكان إنشاء طلباتهم ومتابعتها. تتولى الفرق المخولة التصنيف والتعيين وتغيير الحالة.',
            'Créez la demande, précisez priorité et lieu, soumettez, analysez, affectez, acceptez le devis si nécessaire, planifiez l’ordre, documentez les travaux puis résolvez et clôturez.',
            'أنشئ الطلب وحدد الأولوية والمكان ثم أرسله. حلله وعيّنه واقبل العرض عند الحاجة، وجدول أمر العمل ووثق الأشغال ثم عالج وأغلق.',
            'Demande: brouillon, soumise, en analyse, approuvée/rejetée, en cours, résolue, clôturée/annulée. La réouverture après résolution est limitée. Les notes internes ne sont jamais montrées au résident.',
            'حالات الطلب: مسودة، مرسل، قيد المراجعة، مقبول/مرفوض، جار، محلول، مغلق/ملغى. إعادة الفتح محدودة زمنيا، والملاحظات الداخلية لا تظهر للمقيم.',
            'view_maintenance_requests', ['maintenance.dashboard', 'maintenance.requests.index', 'maintenance.requests.show', 'portal.maintenance.index'], ['maintenance', 'incident', 'ordre de travail', 'devis'], ['صيانة', 'حادث', 'أمر عمل', 'عرض سعر'], ['maintenance'],
        ),
        'governance-workflow' => $module(
            'workflows', 60, 'Préparer et tenir une assemblée', 'إعداد الجمع العام وعقده',
            'Le module conserve préparation, ordre du jour, électorat, convocations, présence, procurations, votes, procès-verbal et exécution des résolutions.',
            'تحفظ الوحدة الإعداد وجدول الأعمال والهيئة الناخبة والاستدعاءات والحضور والوكالات والتصويت والمحضر وتنفيذ القرارات.',
            'Les actions sensibles ont des permissions séparées: préparation, revue, approbation, quorum, vote, procès-verbal et finalisation.',
            'للإجراءات الحساسة صلاحيات منفصلة: الإعداد والمراجعة والموافقة والنصاب والتصويت والمحضر والإنهاء.',
            'Créez l’assemblée, préparez l’ordre du jour, figez l’éligibilité, contrôlez, approuvez et envoyez la convocation. En séance, enregistrez présence/procurations, confirmez le quorum, votez, préparez et approuvez le PV, puis suivez les actions.',
            'أنشئ الجمع وهيئ جدول الأعمال وثبّت الأهلية وراجعها ثم وافق على الاستدعاء وأرسله. أثناء الجلسة سجل الحضور والوكالات وأكد النصاب والتصويت، ثم حضر المحضر واعتمده وتابع الإجراءات.',
            'Les instantanés et versions garantissent la traçabilité. Une correction de vote crée une trace. Une résolution contestée peut être suspendue; elle n’est pas effacée.',
            'تضمن اللقطات والإصدارات التتبع. ينشئ تصحيح التصويت أثرا، ويمكن تعليق القرار المطعون فيه دون حذفه.',
            'view_assemblies', ['governance.dashboard', 'governance.index', 'governance.show', 'owner-governance.index'], ['assemblée', 'quorum', 'vote', 'procès-verbal', 'convocation'], ['جمع عام', 'نصاب', 'تصويت', 'محضر', 'استدعاء'], ['governance'],
        ),
        'accounting-closing-workflow' => $module(
            'workflows', 70, 'Valider, rapprocher et clôturer la comptabilité', 'اعتماد المحاسبة ومطابقتها وإقفالها',
            'La comptabilité transforme les sources métier en écritures équilibrées puis produit journaux, grand livre, balance et dossier de clôture.',
            'تحول المحاسبة المصادر التشغيلية إلى قيود متوازنة ثم تنتج اليوميات والأستاذ والميزان وملف الإقفال.',
            'Cadre adopté, plan de comptes, journaux, exercice et périodes configurés. Les droits de saisie, validation, extourne, verrouillage et clôture sont distincts.',
            'يلزم اعتماد الإطار ودليل الحسابات واليوميات والسنة والفترات. صلاحيات الإدخال والترحيل والعكس والقفل والإقفال منفصلة.',
            'Contrôlez les sources, corrigez les correspondances, comptabilisez, rapprochez banque/caisse et sous-ledgers, analysez les écarts, verrouillez la période, préparez puis approuvez et exécutez la clôture.',
            'راجع المصادر وصحح ربط الحسابات ورحّل القيود، ثم طابق البنك والصندوق والسجلات الفرعية وحلل الفروق، واقفل الفترة وحضر الإقفال وراجعه واعتمده ونفذه.',
            'Une écriture comptabilisée n’est jamais modifiée: elle est extournée. La validation métier n’équivaut pas à la clôture comptable. La réouverture suit une demande, une approbation et une exécution tracées.',
            'لا يعدل القيد المرحّل بل يُعكس. الاعتماد التشغيلي لا يساوي الإقفال المحاسبي. إعادة الفتح تمر بطلب وموافقة وتنفيذ موثق.',
            'view_accounting_configuration', ['accounting.index', 'accounting.reports.index', 'accounting.closing.index'], ['comptabilité', 'rapprochement', 'clôture', 'extourne', 'balance'], ['محاسبة', 'مطابقة', 'إقفال', 'عكس', 'ميزان'], ['accounting', 'accounting-reconciliation'],
        ),
        'documents-communication-workflow' => $module(
            'workflows', 80, 'Publier documents et communications', 'نشر المستندات والتواصل',
            'Les documents de résidence sont versionnés et publiés à une audience; les annonces sont des communications datées et ciblées.',
            'مستندات الإقامة ذات إصدارات وتنشر لجمهور محدد، أما الإعلانات فهي رسائل مؤرخة وموجهة.',
            'Les permissions de voir, gérer et publier sont séparées. Une résidence active est requise.',
            'صلاحيات العرض والإدارة والنشر منفصلة، ويلزم اختيار إقامة نشطة.',
            'Créez le document, ajoutez une version, choisissez catégorie et audience, puis publiez. Pour une annonce, rédigez les deux langues utiles, choisissez priorité, audience et date, puis publiez ou planifiez.',
            'أنشئ المستند وأضف إصدارا وحدد الفئة والجمهور ثم انشر. للإعلان اكتب اللغتين المطلوبتين وحدد الأولوية والجمهور والتاريخ ثم انشر أو جدوِل.',
            'Un document opérationnel n’est une preuve comptable que s’il est généré/rattaché au flux financier correspondant. Une publication échouée reste signalée et doit être résolue sans contourner le contrôle.',
            'لا يصبح المستند التشغيلي دليلا محاسبيا إلا إذا وُلد أو رُبط بالمسار المالي المناسب. يبقى فشل النشر ظاهرا ويجب علاجه دون تجاوز الضابط.',
            'view_documents', ['documents.index', 'announcements.index', 'portal.documents', 'portal.announcements'], ['document', 'annonce', 'avis', 'publication'], ['مستند', 'إعلان', 'إشعار', 'نشر'], ['documents-announcements'],
        ),
        'property-structure' => $module(
            'modules', 10, 'Résidences, bâtiments et lots', 'الإقامات والمباني والوحدات',
            'La résidence contient des bâtiments; un bâtiment peut contenir entrées et étages; le lot est l’unité juridiquement ou opérationnellement gérée.',
            'تحتوي الإقامة مباني، وقد يضم المبنى مداخل وطوابق، والوحدة هي الأصل المُدار قانونيا أو تشغيليا.',
            'Permission de structure et résidence active. Le lot exige une référence unique dans la résidence et un type parmi appartement, villa, commerce, bureau, garage, parking, dépôt ou autre.',
            'يلزم إذن إدارة الهيكل وإقامة نشطة. تحتاج الوحدة مرجعا فريدا داخل الإقامة ونوعا معتمدا مثل شقة أو فيلا أو محل أو مكتب أو مرأب.',
            'Structure > ajoutez bâtiment, entrée/étage si utile, puis lots un par un ou par création groupée (500 maximum). Affectez ensuite propriété, occupation et valeurs de répartition.',
            'الهيكل > أضف المبنى ثم المدخل والطابق عند الحاجة، ثم الوحدات منفردة أو جماعيا بحد 500. بعدها اربط الملكية والإشغال وقيم التوزيع.',
            'Une résidence n’est pas un bâtiment et un lot n’est pas un occupant. Désactiver ou archiver conserve l’historique. Exemple: Résidence Al Qods > Bâtiment A > Entrée 1 > lot A-12.',
            'الإقامة ليست مبنى، والوحدة ليست ساكنا. التعطيل أو الأرشفة يحفظ التاريخ. مثال: إقامة القدس > المبنى أ > المدخل 1 > الوحدة A-12.',
            'manage_property_structure', ['structure.index', 'lots.show'], ['lot', 'unité', 'bâtiment', 'entrée', 'étage'], ['وحدة', 'مبنى', 'مدخل', 'طابق'], ['residence-setup-workflow', 'contacts-ownership-occupancy'],
        ),
        'contacts-ownership-occupancy' => $module(
            'modules', 20, 'Contacts, propriété et occupation', 'جهات الاتصال والملكية والإشغال',
            'Un contact représente une personne ou société. La propriété relie un propriétaire à un lot et une période; l’occupation relie un occupant au lot et à une période.',
            'تمثل جهة الاتصال شخصا أو شركة. تربط الملكية مالكا بوحدة وفترة، ويربط الإشغال ساكنا بوحدة وفترة.',
            'Permissions distinctes pour contacts, propriétés et occupations. La somme des quotes-parts actives doit rester cohérente; les dates ne doivent pas se chevaucher illégalement.',
            'توجد صلاحيات منفصلة للاتصالات والملكيات والإشغال. يجب اتساق مجموع نسب الملكية النشطة وعدم تداخل الفترات بصورة غير صحيحة.',
            'Créez le contact, ouvrez le lot, transférez/ajoutez la propriété avec date et pourcentage, puis enregistrez l’occupation. Fermez une occupation avec sa date de fin au lieu d’écraser son histoire.',
            'أنشئ جهة الاتصال وافتح الوحدة ثم حوّل أو أضف الملكية بتاريخ ونسبة، وسجل الإشغال. أنهِ الإشغال بتاريخ نهاية بدلا من الكتابة فوق تاريخه.',
            'Propriétaire et occupant peuvent être la même personne mais restent deux relations. Le portail exige un compte utilisateur lié au contact. Exemple: Nadia possède 100 % du lot A-12; Youssef l’occupe comme locataire.',
            'قد يكون المالك والساكن الشخص نفسه لكنهما علاقتان مستقلتان. تتطلب البوابة حساب مستخدم مرتبطا بجهة الاتصال. مثال: نادية تملك 100٪ من A-12 ويوسف يشغلها كمكتري.',
            'manage_contacts', ['contacts.index', 'contacts.show', 'lots.show'], ['propriétaire', 'résident', 'occupant', 'propriété', 'occupation'], ['مالك', 'مقيم', 'شاغل', 'ملكية', 'إشغال'], ['property-structure', 'import-workflow'],
        ),
        'allocation-keys' => $module(
            'modules', 30, 'Clés de répartition', 'مفاتيح التوزيع',
            'Une clé porte une valeur par lot et répartit une charge selon les tantièmes ou une base métier.',
            'يحمل مفتاح التوزيع قيمة لكل وحدة ويوزع المصروف حسب الحصص أو أساس تشغيلي.',
            'Permission de gérer les clés, résidence et lots actifs. Une catégorie de charges peut référencer une clé par défaut.',
            'يلزم إذن إدارة المفاتيح وإقامة ووحدات نشطة. يمكن لفئة المصاريف تحديد مفتاح افتراضي.',
            'Allocations > créez la clé > saisissez ou importez les valeurs de tous les lots > contrôlez le total > associez-la aux catégories. Utilisez une date d’effet quand elle est proposée.',
            'التوزيعات > أنشئ المفتاح > أدخل أو استورد قيم جميع الوحدات > راجع المجموع > اربطه بالفئات. استعمل تاريخ السريان عند توفره.',
            'Une clé incomplète peut bloquer l’exploitation d’une résidence ou produire des lots sans part. Corrigez les valeurs avant de valider l’appel de fonds; ne modifiez pas rétroactivement une distribution validée.',
            'قد يمنع المفتاح الناقص تشغيل الإقامة أو يترك وحدات بلا حصة. صحح القيم قبل اعتماد نداء الأموال ولا تغير توزيعا معتمدا بأثر رجعي.',
            'manage_allocation_keys', ['allocations.index'], ['tantièmes', 'quote-part', 'répartition'], ['حصص', 'نسبة', 'توزيع'], ['fund-calls', 'property-structure'],
        ),
        'financial-setup' => $module(
            'modules', 40, 'Exercices, comptes et catégories', 'السنوات والحسابات والفئات',
            'L’exercice borne les opérations. Les comptes représentent banque ou caisse. Les catégories classent les charges et portent leur clé par défaut.',
            'تحدد السنة نطاق العمليات. تمثل الحسابات البنك أو الصندوق، وتصنف الفئات المصاريف وتحمل مفتاحها الافتراضي.',
            'Permissions dédiées à chaque configuration et résidence active. Les dates d’exercice doivent être cohérentes.',
            'صلاحيات مستقلة لكل إعداد مع إقامة نشطة، ويجب اتساق تواريخ السنة المالية.',
            'Finance > Exercices: créez puis ouvrez. Finance > Comptes: ajoutez banque ou caisse. Catégories: ajoutez le libellé et la clé de répartition. Les soldes d’ouverture comptables passent par le lot d’ouverture lorsque la comptabilité est configurée.',
            'المالية > السنوات: أنشئ ثم افتح. الحسابات: أضف بنكا أو صندوقا. الفئات: أضف التسمية ومفتاح التوزيع. تمر أرصدة الافتتاح عبر دفعة الافتتاح عند ضبط المحاسبة.',
            'La fermeture d’exercice et la clôture comptable sont distinctes. Une réouverture exige un motif. Ne saisissez pas un faux paiement pour créer un solde d’ouverture.',
            'إغلاق السنة التشغيلية مختلف عن الإقفال المحاسبي، وإعادة الفتح تحتاج سببا. لا تسجل دفعة وهمية لإنشاء رصيد افتتاحي.',
            'view_finance', ['financial-exercises.index', 'financial-accounts.index', 'charge-categories.index'], ['exercice', 'compte bancaire', 'caisse', 'catégorie'], ['سنة مالية', 'حساب بنكي', 'صندوق', 'فئة'], ['accounting', 'fund-calls'],
        ),
        'budgets' => $module(
            'modules', 50, 'Budgets', 'الميزانيات',
            'Le budget prévoit des montants par exercice et catégorie. Il ne crée aucune créance tant qu’un appel de fonds n’est pas émis.',
            'تتوقع الميزانية مبالغ حسب السنة والفئة، ولا تنشئ مستحقات قبل إصدار نداء أموال.',
            'Permission de gérer les budgets; approbation séparée. Exercice ouvert et catégories actives.',
            'يلزم إذن إدارة الميزانية، وللاعتماد إذن منفصل، مع سنة مفتوحة وفئات نشطة.',
            'Créez un brouillon, ajoutez les lignes en MAD, soumettez/approuvez, puis verrouillez si nécessaire. Une révision part d’un budget approuvé non verrouillé et crée une nouvelle version brouillon.',
            'أنشئ مسودة وأضف البنود بالدرهم ثم اعتمدها واقفلها عند الحاجة. تبدأ المراجعة من ميزانية معتمدة غير مقفلة وتنشئ إصدار مسودة جديدا.',
            'Statuts: brouillon, approuvé, verrouillé, archivé. Déverrouiller exige une autorisation élevée et laisse une trace. Exemple: entretien ascenseur 24 000 MAD prévu, sans dette de copropriétaire avant appel.',
            'الحالات: مسودة، معتمدة، مقفلة، مؤرشفة. يتطلب فك القفل صلاحية عالية ويترك أثرا. مثال: 24,000 درهم لصيانة المصعد دون دين على الملاك قبل النداء.',
            'manage_budgets', ['budgets.index', 'budgets.show'], ['budget', 'prévision', 'révision'], ['ميزانية', 'توقع', 'مراجعة'], ['finance-workflow', 'fund-calls'],
        ),
        'fund-calls' => $module(
            'modules', 60, 'Appels de fonds et échéanciers', 'نداءات الأموال والجداول',
            'L’appel transforme des lignes à répartir en créances par lot. L’échéancier prépare des émissions répétées.',
            'يحول النداء بنود التوزيع إلى مستحقات لكل وحدة، ويهيئ الجدول الإصدارات المتكررة.',
            'Exercice en brouillon/ouvert, catégories, lots, propriétaires et clés. Création, validation et annulation ont des permissions distinctes.',
            'يلزم سنة مسودة أو مفتوحة وفئات ووحدات وملاك ومفاتيح. صلاحيات الإنشاء والاعتماد والإلغاء مستقلة.',
            'Créez le brouillon, fixez dates, cible et méthode (clé, égal, fixe ou manuel), contrôlez l’aperçu puis validez. Générez le PDF depuis un appel validé ou clôturé.',
            'أنشئ المسودة وحدد التواريخ والهدف وطريقة التوزيع (مفتاح، بالتساوي، ثابت أو يدوي)، راجع المعاينة ثم اعتمد. أنشئ PDF من نداء معتمد أو مغلق.',
            'Validation crée les charges. Annulez par le flux prévu; ne supprimez pas les créances. Budget et appel diffèrent: prévision contre exigibilité réelle.',
            'ينشئ الاعتماد المستحقات. ألغ عبر المسار المخصص ولا تحذف الديون. الميزانية توقع، أما النداء فينشئ الاستحقاق الفعلي.',
            'view_finance', ['fund-calls.index', 'fund-calls.show', 'fund-call-schedules.index'], ['appel de fonds', 'charge', 'échéancier'], ['نداء أموال', 'مستحق', 'جدول'], ['budgets', 'payments-credit'],
        ),
        'payments-credit' => $module(
            'modules', 70, 'Paiements, affectations et crédit', 'الدفعات والتخصيص والرصيد',
            'Le paiement constate l’encaissement; l’affectation applique tout ou partie à une charge; le reliquat validé devient crédit disponible.',
            'تثبت الدفعة التحصيل، ويطبق التخصيص جزءا منها أو كلها على مستحق، ويصبح الباقي المعتمد رصيدا متاحا.',
            'Compte financier et exercice ouverts. Saisie, validation, extourne et affectation utilisent des permissions séparées.',
            'يلزم حساب مالي وسنة مفتوحة، ولكل من الإدخال والاعتماد والعكس والتخصيص صلاحية منفصلة.',
            'Enregistrez payeur, date, montant, mode, compte et référence. Validez puis affectez en FIFO ou manuellement. Un paiement inconnu reste non affecté jusqu’à identification du payeur; ne devinez pas.',
            'سجل الدافع والتاريخ والمبلغ والطريقة والحساب والمرجع. اعتمد ثم خصص بالأقدم أو يدويا. تبقى الدفعة المجهولة دون تخصيص حتى تحديد صاحبها ولا تخمّن.',
            'Brouillon corrigible; validé produit une preuve; inversé conserve l’original et crée la correction. La suppression n’est pas une méthode de correction. Exemple: 1 500 MAD reçus, 1 200 affectés, 300 MAD de crédit.',
            'المسودة قابلة للتصحيح؛ المعتمد ينتج دليلا؛ المعكوس يحفظ الأصل وينشئ التصحيح. الحذف ليس وسيلة تصحيح. مثال: 1,500 درهم، خُصص 1,200 وبقي 300 رصيد.',
            'view_finance', ['payments.index', 'payments.show', 'finance.outstanding', 'finance.statements'], ['paiement', 'affectation', 'crédit', 'reçu', 'inconnu'], ['دفعة', 'تخصيص', 'رصيد', 'وصل', 'مجهول'], ['finance-workflow', 'accounting-reconciliation'],
        ),
        'suppliers-contracts' => $module(
            'modules', 80, 'Fournisseurs et contrats', 'الموردون والعقود',
            'Le fournisseur porte l’identité et les données de règlement; le contrat définit service, durée, montant et pièces. Un renouvellement crée un nouveau contrat lié.',
            'يحمل المورد الهوية وبيانات الأداء، ويحدد العقد الخدمة والمدة والمبلغ والمرفقات. ينشئ التجديد عقدا جديدا مرتبطا.',
            'Voir/gérer les fournisseurs, voir les données privées et gérer les contrats sont des permissions distinctes.',
            'صلاحيات عرض المورد وإدارته وعرض بياناته الخاصة وإدارة العقود منفصلة.',
            'Créez le fournisseur en évitant les doublons, puis le contrat avec résidence, catégorie, dates et renouvellement. Ajoutez les annexes privées. Pour renouveler, utilisez l’action dédiée.',
            'أنشئ المورد بعد التحقق من التكرار، ثم العقد بالإقامة والفئة والتواريخ والتجديد. أضف الملاحق الخاصة واستعمل إجراء التجديد المخصص.',
            'Contrat et renouvellement ne sont pas le même enregistrement. Les statuts et alertes d’expiration conservent la chaîne. Archiver un fournisseur ne supprime ni factures ni contrats.',
            'العقد والتجديد ليسا السجل نفسه. تحفظ الحالات وتنبيهات الانتهاء السلسلة. أرشفة المورد لا تحذف فواتيره أو عقوده.',
            'view_suppliers', ['suppliers.index', 'suppliers.show', 'supplier-contracts.index', 'supplier-contracts.show'], ['fournisseur', 'contrat', 'renouvellement'], ['مورد', 'عقد', 'تجديد'], ['supplier-workflow', 'supplier-invoices'],
        ),
        'supplier-invoices' => $module(
            'modules', 90, 'Factures, engagements et avoirs', 'الفواتير والالتزامات والإشعارات الدائنة',
            'L’engagement autorise une dépense prévue; la facture constate la dette fournisseur; l’avoir réduit cette dette.',
            'يجيز الالتزام نفقة متوقعة، وتثبت الفاتورة دين المورد، ويخفض الإشعار الدائن ذلك الدين.',
            'Exercice ouvert, fournisseur, catégorie et résidence. Les validations et annulations sont séparées de la saisie.',
            'يلزم سنة مفتوحة ومورد وفئة وإقامة، وصلاحيات الاعتماد والإلغاء منفصلة عن الإدخال.',
            'Créez l’engagement si requis, saisissez facture, référence unique, dates, lignes, TVA/remises et pièce originale. Validez après contrôle. Affectez ensuite un avoir à la facture si nécessaire.',
            'أنشئ الالتزام عند الحاجة، وأدخل الفاتورة ومرجعها الفريد والتواريخ والبنود والضريبة والخصم والأصل المرفق. اعتمد بعد المراجعة، وخصص إشعارا دائنا عند الحاجة.',
            'Statuts de facture: brouillon puis validée, partielle/payée ou annulée selon les opérations. Une pièce validée ne se modifie pas. Exemple: facture nettoyage 3 600 MAD, avoir 300 MAD, reste 3 300 MAD.',
            'حالات الفاتورة تبدأ بمسودة ثم معتمدة وجزئية/مؤداة أو ملغاة حسب العمليات. لا تعدل الفاتورة المعتمدة. مثال: تنظيف 3,600 درهم، إشعار 300، الباقي 3,300.',
            'view_expenses', ['expense-commitments.index', 'supplier-invoices.index', 'supplier-invoices.show', 'supplier-credit-notes.index'], ['facture fournisseur', 'engagement', 'avoir', 'TVA'], ['فاتورة مورد', 'التزام', 'إشعار دائن', 'ضريبة'], ['suppliers-contracts', 'supplier-settlements'],
        ),
        'supplier-settlements' => $module(
            'modules', 100, 'Règlements et exigibles fournisseurs', 'تسويات ومستحقات الموردين',
            'L’exigible calcule ce qui reste dû; le règlement représente la sortie de banque/caisse et ses affectations.',
            'يحسب المستحق ما تبقى واجبا، وتمثل التسوية الخروج من البنك أو الصندوق وتخصيصاته.',
            'Facture validée, compte financier et permission de règlement. La validation et l’inversion sont séparées.',
            'يلزم فاتورة معتمدة وحساب مالي وإذن التسوية، وللاعتماد والعكس صلاحيات مستقلة.',
            'Consultez Exigibles, créez le règlement, choisissez compte et mode, puis affectez FIFO ou manuellement sans dépasser les soldes. Validez et générez le bon.',
            'راجع المستحقات وأنشئ التسوية واختر الحساب والطريقة ثم خصص بالأقدم أو يدويا دون تجاوز الأرصدة. اعتمد وأنشئ سند الأداء.',
            'Un règlement validé se corrige par inversion, jamais par suppression. L’inversion restaure les soldes et conserve la preuve et l’audit.',
            'تُصحح التسوية المعتمدة بالعكس لا بالحذف. يعيد العكس الأرصدة ويحفظ الدليل وسجل التدقيق.',
            'view_supplier_payables', ['supplier-payables.index', 'supplier-settlements.index', 'supplier-settlements.show'], ['règlement', 'exigible', 'allocation fournisseur'], ['تسوية', 'مستحق', 'تخصيص مورد'], ['supplier-invoices', 'accounting-reconciliation'],
        ),
        'maintenance' => $module(
            'modules', 110, 'Maintenance et interventions', 'الصيانة والتدخلات',
            'Catégories, demandes, devis, ordres, équipements et plans préventifs couvrent l’incident jusqu’à la validation des travaux.',
            'تغطي الفئات والطلبات والعروض والأوامر والمعدات والخطط الوقائية الحادث حتى اعتماد الأشغال.',
            'Les permissions séparent consultation, gestion, affectation, devis, ordres, équipements et préventif. Le résident ne voit que son périmètre.',
            'تفصل الصلاحيات العرض والإدارة والتعيين والعروض والأوامر والمعدات والوقائي، ولا يرى المقيم إلا نطاقه.',
            'Utilisez la demande pour le besoin, le devis pour l’offre, l’ordre pour l’exécution, l’équipement pour l’actif et le plan pour les échéances récurrentes.',
            'استعمل الطلب للحاجة، والعرض للاقتراح، والأمر للتنفيذ، والمعدة للأصل، والخطة للمواعيد المتكررة.',
            'Les transitions et SLA sont historisés. Une pièce « résident » est visible au demandeur; une pièce « interne » reste privée. Une facture de travaux passe ensuite par le module fournisseur.',
            'تؤرشف التحولات وآجال الخدمة. المرفق الموجه للمقيم ظاهر له، والداخلي خاص. تمر فاتورة الأشغال لاحقا عبر وحدة الموردين.',
            'view_maintenance_requests', ['maintenance.dashboard', 'maintenance.requests.index', 'maintenance.work-orders.index', 'maintenance.equipment.index', 'maintenance.preventive.index'], ['demande', 'devis', 'ordre de travail', 'équipement', 'préventif'], ['طلب', 'عرض', 'أمر عمل', 'معدة', 'وقائي'], ['maintenance-workflow', 'supplier-invoices'],
        ),
        'governance' => $module(
            'modules', 120, 'Gouvernance et assemblées', 'الحكامة والجمع العام',
            'Règles, mandats, assemblées, convocations, votes, procès-verbaux, décisions et actions forment un dossier probant versionné.',
            'تكوّن القواعد والولايات والجمع والاستدعاءات والتصويت والمحاضر والقرارات والإجراءات ملفا موثقا ذا إصدارات.',
            'Les droits fins suivent la séparation des tâches. Le portail propriétaire montre seulement les éléments publiés et pertinents à son électorat.',
            'تطبق الصلاحيات الدقيقة فصل المهام، ولا تعرض بوابة المالك إلا العناصر المنشورة المرتبطة بهيئته الناخبة.',
            'Configurez règles et mandat, créez l’assemblée, suivez la préparation puis la séance et l’exécution. Exportez le registre quand le dossier est complet.',
            'اضبط القواعد والولاية، وأنشئ الجمع وتابع الإعداد ثم الجلسة والتنفيذ. صدّر السجل بعد اكتمال الملف.',
            'Les corrections créent versions, transitions ou événements. Ne remplacez pas une convocation, un résultat ou un PV final par un fichier non tracé.',
            'تنشئ التصحيحات إصدارات أو تحولات أو أحداثا. لا تستبدل استدعاء أو نتيجة أو محضرا نهائيا بملف غير موثق.',
            'view_governance_dashboard', ['governance.dashboard', 'governance.rules.index', 'governance.mandates.index', 'governance.index'], ['gouvernance', 'mandat', 'résolution', 'registre'], ['حكامة', 'ولاية', 'قرار', 'سجل'], ['governance-workflow'],
        ),
        'documents-announcements' => $module(
            'modules', 130, 'Documents, annonces et notifications', 'المستندات والإعلانات والإشعارات',
            'Le document publie une pièce versionnée; l’annonce informe; la notification signale un événement dans l’application.',
            'ينشر المستند ملفا ذا إصدارات، ويبلّغ الإعلان، وينبه الإشعار إلى حدث داخل التطبيق.',
            'Audience et permissions contrôlent la visibilité. Les préférences de notification n’accordent jamais un nouvel accès.',
            'يتحكم الجمهور والصلاحيات في الرؤية، ولا تمنح تفضيلات الإشعار أي وصول جديد.',
            'Choisissez la nature correcte, l’audience et la langue. Vérifiez le portail après publication. Utilisez une annonce pour l’information et un document/flux de convocation pour une notification formelle.',
            'اختر النوع والجمهور واللغة الصحيحة، وراجع البوابة بعد النشر. استعمل الإعلان للمعلومة والمستند أو مسار الاستدعاء للتبليغ الرسمي.',
            'La publication fige un instantané d’audience quand le flux le prévoit. Les versions remplacées restent dans l’historique. Les notifications ne remplacent pas une preuve de remise légale.',
            'يثبت النشر لقطة الجمهور عندما يقتضي المسار. تبقى الإصدارات السابقة في السجل، ولا يحل الإشعار محل إثبات التبليغ القانوني.',
            'view_documents', ['documents.index', 'announcements.index', 'notifications.index', 'portal.index'], ['annonce', 'avis formel', 'notification', 'version'], ['إعلان', 'تبليغ رسمي', 'إشعار', 'إصدار'], ['documents-communication-workflow'],
        ),
        'accounting' => $module(
            'modules', 140, 'Comptabilité et automatisation', 'المحاسبة والأتمتة',
            'Cadre, régime, plan de comptes, journaux, périodes et règles de correspondance structurent les écritures manuelles et automatiques.',
            'ينظم الإطار والنظام ودليل الحسابات واليوميات والفترات وقواعد الربط القيود اليدوية والآلية.',
            'Les permissions distinguent configuration, saisie, comptabilisation, extourne, règles brouillon, revue et activation.',
            'تفصل الصلاحيات الإعداد والإدخال والترحيل والعكس ومسودة القواعد ومراجعتها وتفعيلها.',
            'Adoptez le cadre, consignez l’évaluation de régime, configurez comptes/journaux/exercice, vérifiez les mappings, testez les sources puis activez les règles revues.',
            'اعتمد الإطار وسجل تقييم النظام واضبط الحسابات واليوميات والسنة، وراجع الربط واختبر المصادر ثم فعّل القواعد المراجعة.',
            'Une écriture doit être équilibrée. Brouillon modifiable; comptabilisée immuable; correction par extourne. Les diagnostics signalent les sources non comptabilisées sans les masquer.',
            'يجب توازن القيد. المسودة قابلة للتعديل، والمرحّل ثابت، وتصحيحه بالعكس. تكشف التشخيصات المصادر غير المرحلة دون إخفائها.',
            'view_accounting_configuration', ['accounting.index'], ['plan comptable', 'journal', 'écriture', 'mapping', 'automatisation'], ['دليل الحسابات', 'يومية', 'قيد', 'ربط', 'أتمتة'], ['accounting-closing-workflow', 'accounting-reconciliation'],
        ),
        'accounting-reconciliation' => $module(
            'modules', 150, 'Rapports, rapprochement et clôture', 'التقارير والمطابقة والإقفال',
            'Les rapports comparent journaux, grand livre, balance, tiers, budget/réel et sous-ledgers. La clôture gèle une période après contrôles.',
            'تقارن التقارير اليوميات والأستاذ والميزان والأطراف والميزانية بالفعلي والسجلات الفرعية. يجمد الإقفال الفترة بعد الضوابط.',
            'Chaque rapport et étape de clôture possède sa permission. L’export peut être autorisé sans droit de modification.',
            'لكل تقرير ومرحلة إقفال صلاحية، ويمكن السماح بالتصدير دون التعديل.',
            'Fixez exercice/période, analysez les écarts, rapprochez finance résidents et fournisseurs avec le grand livre, résolvez les blocages de préparation, puis suivez revue, approbation, exécution et report à nouveau.',
            'حدد السنة والفترة وحلل الفروق، وطابق مالية السكان والموردين مع الأستاذ، وعالج موانع التحضير، ثم تابع المراجعة والموافقة والتنفيذ والترحيل.',
            'Le rapprochement explique un écart; il ne le supprime pas. Une période verrouillée bloque les mutations. Toute réouverture est tracée et ne doit pas servir à réécrire une preuve.',
            'تفسر المطابقة الفرق ولا تخفيه. تمنع الفترة المقفلة التغييرات. كل إعادة فتح موثقة ولا تستعمل لإعادة كتابة الدليل.',
            'view_accounting_reconciliation', ['accounting.reports.index', 'accounting.closing.index'], ['rapport', 'grand livre', 'balance', 'rapprochement', 'clôture'], ['تقرير', 'أستاذ', 'ميزان', 'مطابقة', 'إقفال'], ['accounting', 'payments-credit', 'supplier-settlements'],
        ),
        'compliance' => $module(
            'modules', 160, 'Conformité et conservation des preuves', 'الامتثال وحفظ الأدلة',
            'Sources, autorités, modèles versionnés, applicabilité, obligations, échéances, soumissions, preuves et rappels composent le registre de conformité.',
            'تكوّن المصادر والسلطات والنماذج ذات الإصدارات والقابلية والالتزامات والآجال والإيداعات والأدلة والتذكيرات سجل الامتثال.',
            'Les droits distinguent création de modèle, vérification de source, approbation/activation, affectation, soumission, preuve et export.',
            'تفصل الصلاحيات إنشاء النموذج والتحقق من المصدر والموافقة والتفعيل والتعيين والإيداع والدليل والتصدير.',
            'Enregistrez la source officielle et son autorité, faites revoir puis activer la version, évaluez l’applicabilité, générez et assignez l’obligation, déposez soumission et preuve, puis changez l’état.',
            'سجل المصدر الرسمي وسلطته، وراجع إصدار النموذج ثم فعّله، وقيّم القابلية وأنشئ الالتزام وعيّنه، وسجل الإيداع والدليل ثم غيّر الحالة.',
            'Une preuve est versionnée avec intégrité; ne remplacez pas l’original. Les échéances forcées et décisions d’applicabilité sont auditées. L’export du registre ne modifie aucun état.',
            'الدليل ذو إصدارات محمية ولا يستبدل الأصل. تُدقق تغييرات الآجال وقرارات القابلية، ولا يغير تصدير السجل أي حالة.',
            'view_compliance_calendar', ['compliance.index', 'compliance.obligations.show'], ['conformité', 'obligation', 'preuve', 'échéance', 'rétention'], ['امتثال', 'التزام', 'دليل', 'أجل', 'حفظ'], ['accounting-closing-workflow'],
        ),
        'reports-portals' => $module(
            'modules', 170, 'Rapports, exports et portails', 'التقارير والتصدير والبوابات',
            'Les rapports servent au pilotage; les exports produisent des fichiers; les portails donnent au propriétaire/résident une vue strictement limitée à ses lots et publications.',
            'تخدم التقارير التسيير، وتنتج التصديرات ملفات، وتمنح البوابات للمالك أو المقيم عرضا محدودا بوحداته ومنشوراته.',
            'Les permissions de consultation et d’export sont distinctes. Le rôle copropriétaire exige un contact lié et une propriété/occupation active selon l’écran.',
            'صلاحيات العرض والتصدير مستقلة. يتطلب دور المالك المشترك جهة اتصال مرتبطة وملكية أو إشغالا نشطا حسب الشاشة.',
            'Choisissez la résidence et les filtres, contrôlez totaux et période, puis exportez. Dans le portail, vérifiez soldes, paiements, documents, annonces, maintenance et assemblées disponibles.',
            'اختر الإقامة والمرشحات وراجع المجاميع والفترة ثم صدّر. في البوابة راجع الأرصدة والدفعات والمستندات والإعلانات والصيانة والجمع المتاح.',
            'Un export est un instantané, pas une nouvelle source comptable. Un ancien propriétaire perd l’accès aux documents privés lorsque son droit prend fin, sauf règle explicite du flux.',
            'التصدير لقطة وليس مصدرا محاسبيا جديدا. يفقد المالك السابق الوصول إلى المستندات الخاصة بعد انتهاء حقه ما لم ينص المسار صراحة.',
            'view_residences', ['dashboard', 'portal.index', 'owner-finance.index', 'owner-governance.index'], ['rapport', 'export', 'portail propriétaire', 'portail résident'], ['تقرير', 'تصدير', 'بوابة المالك', 'بوابة المقيم'], ['documents-announcements', 'accounting-reconciliation'],
        ),
        'role-owner' => $module(
            'roles', 10, 'Guide du propriétaire de l’organisation', 'دليل مالك المؤسسة',
            'Le rôle owner dispose de toutes les permissions de l’organisation et assume la délégation, la configuration et les contrôles sensibles.',
            'يملك دور مالك المؤسسة جميع صلاحياتها ويتحمل التفويض والإعداد والضوابط الحساسة.',
            'Réservé au propriétaire de l’organisation. Il peut attribuer les autres rôles et permissions explicites.',
            'مخصص لمالك المؤسسة، ويمكنه منح الأدوار الأخرى والصلاحيات الصريحة.',
            'Chaque jour: surveiller alertes et exceptions. Chaque période: revoir droits, rapprochements, validations et clôtures. Déléguez la saisie et gardez les approbations sensibles séparées.',
            'يوميا: راقب التنبيهات والاستثناءات. دوريا: راجع الحقوق والمطابقات والاعتمادات والإقفالات. فوّض الإدخال وافصل الموافقات الحساسة.',
            'Évitez le compte partagé et les actions courantes avec un pouvoir maximal. Les restrictions de résidence restent essentielles pour les collaborateurs.',
            'تجنب الحساب المشترك والأعمال اليومية بصلاحيات قصوى. تبقى قيود الإقامة ضرورية للمتعاونين.',
            null, [], ['owner', 'propriétaire organisation', 'super administrateur'], ['مالك المؤسسة', 'مدير أعلى'], ['getting-started'], ['owner'],
        ),
        'role-administrator' => $module(
            'roles', 20, 'Guide de l’administrateur syndic', 'دليل مدير السنديك',
            'L’administrateur pilote structure, équipe, finance, fournisseurs, maintenance, gouvernance, comptabilité et conformité selon la configuration.',
            'يدير مسؤول السنديك الهيكل والفريق والمالية والموردين والصيانة والحكامة والمحاسبة والامتثال حسب الإعداد.',
            'Rôle administrator. Il ne peut pas se substituer au propriétaire de l’organisation pour les délégations réservées.',
            'دور administrator، ولا يحل محل مالك المؤسسة في التفويضات المحجوزة له.',
            'Ordre recommandé: vérifier contexte, traiter alertes, contrôler opérations à valider, suivre impayés/exigibles, maintenance et échéances, puis activité et rapports.',
            'الترتيب: تحقق من السياق، عالج التنبيهات والعمليات المطلوب اعتمادها، تابع المتأخرات ومستحقات الموردين والصيانة والآجال، ثم النشاط والتقارير.',
            'Utilisez la séparation des tâches même si le rôle permet beaucoup d’actions. Les actions finales de clôture et de gouvernance restent traçables.',
            'طبق فصل المهام رغم اتساع الصلاحيات. تبقى إجراءات الإقفال والحكامة النهائية موثقة.',
            null, [], ['administrateur', 'syndic'], ['مدير', 'سنديك'], ['first-use-checklist'], ['administrator'],
        ),
        'role-manager' => $module(
            'roles', 30, 'Guide du gestionnaire', 'دليل المسير',
            'Le gestionnaire assure l’exploitation: immeubles, contacts, appels, dépenses, communications, maintenance et préparation de gouvernance.',
            'يتولى المسير التشغيل: العقارات والاتصالات والنداءات والمصاريف والتواصل والصيانة وإعداد الحكامة.',
            'Rôle manager. Certaines validations financières, règles comptables, conformité sensible et approbations de gouvernance restent indisponibles.',
            'دور manager. لا تتاح له بعض الاعتمادات المالية وقواعد المحاسبة والامتثال الحساس وموافقات الحكامة.',
            'Commencez par demandes et échéances, puis encaissements/impayés, fournisseurs et travaux. Préparez les dossiers complets avant de les transmettre au valideur.',
            'ابدأ بالطلبات والآجال ثم التحصيل والمتأخرات والموردين والأشغال. حضر الملفات كاملة قبل إحالتها للمصادق.',
            'Ne contournez pas une validation absente en changeant le statut ou en recréant l’opération. Demandez au rôle autorisé.',
            'لا تتجاوز اعتمادا غير متاح بتغيير الحالة أو إعادة إنشاء العملية، بل أحلها إلى الدور المخول.',
            null, [], ['gestionnaire', 'property manager'], ['مسير', 'مدير عقار'], ['maintenance-workflow', 'finance-workflow'], ['manager'],
        ),
        'role-accountant' => $module(
            'roles', 40, 'Guide du comptable', 'دليل المحاسب',
            'Le comptable configure et contrôle finance, dépenses et comptabilité; il dispose aussi des fonctions de conformité prévues.',
            'يضبط المحاسب ويراقب المالية والمصاريف والمحاسبة، وله وظائف الامتثال المقررة.',
            'Rôle accountant. La structure immobilière et la gestion opérationnelle de maintenance ne font pas partie de son périmètre par défaut.',
            'دور accountant. لا تشمل صلاحياته الافتراضية الهيكل العقاري أو التشغيل اليومي للصيانة.',
            'Contrôlez les exercices et comptes, validez appels/paiements/factures/règlements, vérifiez les postings, rapprochez les soldes, produisez les rapports puis préparez les clôtures.',
            'راجع السنوات والحسابات واعتمد النداءات والدفعات والفواتير والتسويات وتحقق من الترحيل وطابق الأرصدة وأنتج التقارير ثم حضر الإقفال.',
            'L’écart entre sous-ledger et grand livre doit être expliqué avant clôture. Corrigez par les workflows métier ou l’extourne, jamais par suppression.',
            'يجب تفسير الفرق بين السجل الفرعي والأستاذ قبل الإقفال. صحح عبر مسار العمل أو القيد العكسي لا بالحذف.',
            null, [], ['comptable', 'accountant'], ['محاسب'], ['accounting-closing-workflow'], ['accountant'],
        ),
        'role-maintenance' => $module(
            'roles', 50, 'Guide de l’agent de maintenance', 'دليل مسؤول الصيانة',
            'L’agent traite demandes, devis, ordres, équipements et préventif et consulte les fournisseurs nécessaires.',
            'يعالج مسؤول الصيانة الطلبات والعروض والأوامر والمعدات والوقائي ويطلع على الموردين اللازمين.',
            'Rôle maintenance_agent. Il ne valide pas finance, factures, paiements, gouvernance ou clôture.',
            'دور maintenance_agent، ولا يعتمد المالية أو الفواتير أو الدفعات أو الحكامة أو الإقفال.',
            'Priorisez les urgences et SLA, qualifiez, affectez, planifiez, documentez chaque intervention et séparez notes internes des messages résident.',
            'رتب الطوارئ وآجال الخدمة، وصنف وعيّن وجدول ووثق كل تدخل وافصل الملاحظات الداخلية عن رسائل المقيم.',
            'Ne marquez pas « terminé » sans rapport, ni « validé » avant contrôle. Transmettez la facture au flux fournisseur.',
            'لا تعلّم العمل مكتملا دون تقرير ولا معتمدا قبل المراقبة. أحل الفاتورة إلى مسار الموردين.',
            null, [], ['agent maintenance', 'technicien'], ['مسؤول صيانة', 'تقني'], ['maintenance'], ['maintenance_agent'],
        ),
        'role-auditor' => $module(
            'roles', 60, 'Guide de l’auditeur', 'دليل المدقق',
            'L’auditeur consulte activités, finance, dépenses, maintenance, gouvernance, comptabilité, conformité et exports sans piloter les opérations.',
            'يطلع المدقق على النشاط والمالية والمصاريف والصيانة والحكامة والمحاسبة والامتثال والتصديرات دون تشغيلها.',
            'Rôle auditor, majoritairement en lecture. Les diagnostics et exports autorisés restent soumis au périmètre de résidence.',
            'دور auditor وغالب صلاحياته للقراءة، وتبقى التشخيصات والتصديرات ضمن نطاق الإقامة.',
            'Fixez période et résidence, partez des rapports, remontez aux pièces et événements d’activité, puis exportez les registres nécessaires.',
            'حدد الفترة والإقامة وابدأ بالتقارير ثم ارجع إلى الأدلة وأحداث النشاط وصدّر السجلات اللازمة.',
            'Un export ne prouve pas à lui seul l’exhaustivité. Recoupez pièces, statuts, totaux, versions et traces de correction.',
            'لا يثبت التصدير وحده الاكتمال. قارن الأدلة والحالات والمجاميع والإصدارات وآثار التصحيح.',
            null, [], ['auditeur', 'lecture seule'], ['مدقق', 'قراءة فقط'], ['reports-portals'], ['auditor'],
        ),
        'role-coproprietaire' => $module(
            'roles', 70, 'Guide du copropriétaire ou résident', 'دليل المالك المشترك أو المقيم',
            'Le rôle coproprietaire utilise les portails pour ses lots: solde, paiements, documents, annonces, maintenance et gouvernance publiée.',
            'يستعمل دور coproprietaire البوابات لوحداته: الرصيد والدفعات والمستندات والإعلانات والصيانة والحكامة المنشورة.',
            'Compte lié à un contact et résidence autorisée. La visibilité dépend de la propriété/occupation active et de l’audience publiée.',
            'يلزم حساب مرتبط بجهة اتصال وإقامة مسموحة. تعتمد الرؤية على ملكية أو إشغال نشط والجمهور المنشور.',
            'Consultez l’accueil du portail, vérifiez le relevé et les reçus, téléchargez les documents, lisez les annonces, créez/suivez une demande et consultez vos assemblées.',
            'راجع الصفحة الرئيسية للبوابة والكشف والوصولات، ونزّل المستندات واقرأ الإعلانات وأنشئ طلبا وتابعه واطلع على الجموع الخاصة بك.',
            'Ce rôle ne modifie pas les données de gestion ni les écritures. Un document non publié ou destiné à une autre audience n’est pas accessible.',
            'لا يعدل هذا الدور بيانات الإدارة أو القيود. لا يمكنه الوصول إلى مستند غير منشور أو موجه لجمهور آخر.',
            null, [], ['copropriétaire', 'résident', 'portail'], ['مالك مشترك', 'مقيم', 'بوابة'], ['reports-portals'], ['coproprietaire'],
        ),
        'faq' => $article(
            'faq', 10,
            $language('Questions fréquentes', 'Réponses courtes aux confusions les plus fréquentes.', [
                $section('owner-resident', 'Propriétaire ou occupant ?', 'La propriété porte le droit sur le lot et les appels; l’occupation décrit qui y réside. Enregistrez les deux relations avec leurs dates.'),
                $section('budget-call', 'Budget ou appel de fonds ?', 'Le budget prévoit. L’appel validé répartit et crée les créances.'),
                $section('payment-credit', 'Pourquoi un paiement reste en crédit ?', 'Sa partie non affectée à une charge reste disponible. Identifiez les créances puis utilisez l’affectation.'),
                $section('invoice-settlement', 'Facture ou règlement fournisseur ?', 'La facture crée la dette; le règlement constate la sortie et réduit cette dette.'),
                $section('delete', 'Puis-je supprimer une opération validée ?', 'Non. Utilisez annulation, inversion ou extourne selon le module afin de conserver la preuve.'),
                $section('validation-closing', 'Validation ou clôture ?', 'La validation rend une opération effective. La clôture verrouille une période après rapprochement et contrôles.'),
            ]),
            $language('الأسئلة الشائعة', 'إجابات مختصرة عن أكثر المفاهيم التباسا.', [
                $section('owner-resident', 'مالك أم شاغل؟', 'تثبت الملكية الحق في الوحدة والنداءات، بينما يحدد الإشغال من يسكنها. سجل العلاقتين وتواريخهما.'),
                $section('budget-call', 'ميزانية أم نداء أموال؟', 'الميزانية توقع، والنداء المعتمد يوزع وينشئ المستحقات.'),
                $section('payment-credit', 'لماذا تبقى الدفعة رصيدا؟', 'يبقى الجزء غير المخصص لمستحق رصيدا متاحا. حدد المستحقات ثم استعمل التخصيص.'),
                $section('invoice-settlement', 'فاتورة أم تسوية مورد؟', 'تنشئ الفاتورة الدين، وتثبت التسوية الخروج وتخفض الدين.'),
                $section('delete', 'هل يمكن حذف عملية معتمدة؟', 'لا. استعمل الإلغاء أو العكس حسب الوحدة للحفاظ على الدليل.'),
                $section('validation-closing', 'اعتماد أم إقفال؟', 'يجعل الاعتماد العملية نافذة، ويقفل الإقفال الفترة بعد المطابقة والضوابط.'),
            ]),
            null, [], ['faq', 'différence', 'erreur'], ['أسئلة', 'فرق', 'خطأ'], ['glossary'],
        ),
        'glossary' => $article(
            'glossary', 10,
            $language('Glossaire EvoSyndic', 'Le vocabulaire opérationnel et comptable utilisé dans l’application.', [
                $section('terms-property', 'Immeuble et personnes', 'Résidence: périmètre géré. Bâtiment: construction dans la résidence. Lot: unité gérée. Propriété: droit daté sur le lot. Occupation: présence datée dans le lot.'),
                $section('terms-finance', 'Finance résidents', 'Tantièmes: base de répartition. Appel de fonds: émission créant des charges. Impayé: charge échue non soldée. Crédit: paiement validé non affecté.'),
                $section('terms-supplier', 'Dépenses', 'Engagement: autorisation préalable. Facture: dette fournisseur. Avoir: réduction de dette. Règlement: sortie affectée à une ou plusieurs factures.'),
                $section('terms-accounting', 'Comptabilité', 'Comptabiliser: rendre une écriture définitive. Extourner: créer l’écriture inverse. Rapprocher: comparer et expliquer les écarts. Clôturer: geler une période après contrôles.'),
                $section('terms-evidence', 'Communication et preuve', 'Annonce: information. Avis/convocation: notification formelle selon le flux. Document opérationnel: pièce de travail. Preuve comptable: pièce rattachée et protégée par le flux financier.'),
            ]),
            $language('مصطلحات EvoSyndic', 'المفردات التشغيلية والمحاسبية المستعملة في التطبيق.', [
                $section('terms-property', 'العقار والأشخاص', 'الإقامة: النطاق المُدار. المبنى: بناية داخلها. الوحدة: الأصل المُدار. الملكية: حق مؤرخ في الوحدة. الإشغال: سكن مؤرخ فيها.'),
                $section('terms-finance', 'مالية السكان', 'الحصص: أساس التوزيع. نداء الأموال: إصدار ينشئ المستحقات. المتأخر: مستحق حال غير مسدد. الرصيد: دفعة معتمدة غير مخصصة.'),
                $section('terms-supplier', 'المصاريف', 'الالتزام: ترخيص مسبق. الفاتورة: دين المورد. الإشعار الدائن: تخفيض الدين. التسوية: خروج مخصص لفاتورة أو أكثر.'),
                $section('terms-accounting', 'المحاسبة', 'الترحيل: جعل القيد نهائيا. العكس: إنشاء القيد المعاكس. المطابقة: مقارنة الفروق وتفسيرها. الإقفال: تجميد الفترة بعد الضوابط.'),
                $section('terms-evidence', 'التواصل والدليل', 'الإعلان: معلومة. الإشعار أو الاستدعاء: تبليغ رسمي حسب المسار. المستند التشغيلي: ملف عمل. الدليل المحاسبي: ملف مرتبط ومحمي بالمسار المالي.'),
            ]),
            null, [], ['glossaire', 'définition', 'tantièmes', 'extourne'], ['مصطلحات', 'تعريف', 'حصص', 'عكس'],
        ),
    ],
    'checklist' => [
        'setup-organization' => $check('getting-started', 'Configurer le profil du syndic', 'ضبط ملف السنديك', 'Établir l’identité de l’organisation.', 'تثبيت هوية المؤسسة.', 'Propriétaire ou administrateur.', 'مالك المؤسسة أو المدير.', 'Équipe / paramètres de l’organisation.', 'الفريق / إعدادات المؤسسة.', 'Nom, type et informations disponibles.', 'الاسم والنوع والمعلومات المتاحة.', ['Vérifiez l’organisation active.', 'Complétez les informations.', 'Enregistrez.'], ['تحقق من المؤسسة النشطة.', 'أكمل المعلومات.', 'احفظ.'], 'Compte vérifié et organisation créée.', 'حساب موثق ومؤسسة منشأة.', 'Le profil porte le bon nom.', 'يظهر الاسم الصحيح.', 'Confondre organisation et résidence.', 'الخلط بين المؤسسة والإقامة.', 'Création des résidences et de l’équipe.', 'إنشاء الإقامات والفريق.'),
        'setup-profile' => $check('getting-started', 'Régler compte, langue et sécurité', 'ضبط الحساب واللغة والأمان', 'Sécuriser l’accès et choisir la langue.', 'تأمين الوصول واختيار اللغة.', 'Chaque utilisateur.', 'كل مستخدم.', 'Profil.', 'الملف الشخصي.', 'Nom, e-mail, langue, mot de passe.', 'الاسم والبريد واللغة وكلمة المرور.', ['Ouvrez le profil.', 'Choisissez français ou arabe.', 'Mettez à jour le mot de passe si nécessaire.'], ['افتح الملف.', 'اختر الفرنسية أو العربية.', 'حدّث كلمة المرور عند الحاجة.'], 'Accès au compte.', 'الوصول إلى الحساب.', 'Interface dans la langue choisie.', 'الواجهة باللغة المختارة.', 'Partager un compte entre collègues.', 'مشاركة حساب بين الزملاء.', 'Traçabilité personnelle fiable.', 'تتبع شخصي موثوق.'),
        'setup-residence' => $check('residence-setup-workflow', 'Créer la résidence', 'إنشاء الإقامة', 'Créer le périmètre opérationnel.', 'إنشاء النطاق التشغيلي.', 'Créateur de résidences.', 'من يملك إذن الإنشاء.', 'Résidences > Ajouter.', 'الإقامات > إضافة.', 'Nom, adresse et paramètres proposés.', 'الاسم والعنوان والإعدادات.', ['Créez la résidence.', 'Enregistrez.', 'Sélectionnez-la dans l’en-tête.'], ['أنشئ الإقامة.', 'احفظ.', 'اخترها من الأعلى.'], 'Organisation active.', 'مؤسسة نشطة.', 'Résidence en configuration.', 'إقامة في طور الإعداد.', 'Saisir dans une autre résidence active.', 'الإدخال في إقامة أخرى.', 'Structure et modules par résidence.', 'الهيكل ووحدات الإقامة.'),
        'setup-structure' => $check('property-structure', 'Créer bâtiments, entrées, étages et lots', 'إنشاء المباني والمداخل والطوابق والوحدات', 'Décrire le patrimoine géré.', 'وصف الملك المُدار.', 'Gestionnaire de structure.', 'مسير الهيكل.', 'Structure.', 'الهيكل.', 'Noms, références uniques, types et rattachements.', 'الأسماء والمراجع الفريدة والأنواع والروابط.', ['Ajoutez les bâtiments.', 'Ajoutez entrées/étages utiles.', 'Créez ou générez les lots.', 'Contrôlez les références.'], ['أضف المباني.', 'أضف المداخل والطوابق اللازمة.', 'أنشئ الوحدات.', 'راجع المراجع.'], 'Résidence sélectionnée.', 'إقامة مختارة.', 'Au moins un lot actif.', 'وحدة نشطة واحدة على الأقل.', 'Créer un lot pour un occupant au lieu du bien.', 'إنشاء وحدة للساكن بدل الأصل.', 'Propriété, occupation et répartitions.', 'الملكية والإشغال والتوزيعات.'),
        'setup-contacts' => $check('contacts-ownership-occupancy', 'Ajouter propriétaires et résidents', 'إضافة الملاك والمقيمين', 'Créer les personnes et sociétés liées.', 'إنشاء الأشخاص والشركات المرتبطة.', 'Gestionnaire de contacts.', 'مسير جهات الاتصال.', 'Contacts.', 'جهات الاتصال.', 'Type, identité, coordonnées.', 'النوع والهوية وبيانات الاتصال.', ['Recherchez un doublon.', 'Créez le contact.', 'Ajoutez des coordonnées exactes.'], ['ابحث عن التكرار.', 'أنشئ جهة الاتصال.', 'أضف بيانات صحيحة.'], 'Organisation active.', 'مؤسسة نشطة.', 'Contacts disponibles pour les relations.', 'جهات متاحة للربط.', 'Créer deux fiches pour la même personne.', 'إنشاء سجلين للشخص نفسه.', 'Propriété, occupation, fournisseurs et portails.', 'الملكية والإشغال والموردون والبوابات.'),
        'setup-ownerships' => $check('contacts-ownership-occupancy', 'Affecter propriété et occupation', 'ربط الملكية والإشغال', 'Relier les contacts aux lots avec dates.', 'ربط جهات الاتصال بالوحدات والتواريخ.', 'Gestionnaire des propriétés/occupations.', 'مسير الملكيات والإشغال.', 'Lot > Propriété / Occupation.', 'الوحدة > الملكية / الإشغال.', 'Contact, date, pourcentage, rôle d’occupation.', 'جهة الاتصال والتاريخ والنسبة وصفة الإشغال.', ['Ouvrez le lot.', 'Enregistrez la propriété active.', 'Ajoutez l’occupation ou laissez vacant.', 'Contrôlez les périodes.'], ['افتح الوحدة.', 'سجل الملكية النشطة.', 'أضف الإشغال أو اتركها شاغرة.', 'راجع الفترات.'], 'Lots et contacts.', 'وحدات وجهات اتصال.', 'Au moins un propriétaire actif.', 'مالك نشط واحد على الأقل.', 'Écraser l’ancien propriétaire au lieu de transférer.', 'استبدال المالك السابق بدل التحويل.', 'Appels, portails et gouvernance.', 'النداءات والبوابات والحكامة.'),
        'setup-suppliers' => $check('suppliers-contracts', 'Créer fournisseurs et contrats', 'إنشاء الموردين والعقود', 'Préparer les tiers de dépense.', 'تهيئة أطراف المصاريف.', 'Gestionnaire des fournisseurs.', 'مسير الموردين.', 'Dépenses > Fournisseurs / Contrats.', 'المصاريف > الموردون / العقود.', 'Identité, fiscalité, paiement; objet, résidence et dates.', 'الهوية والجباية والأداء؛ الموضوع والإقامة والتواريخ.', ['Créez le fournisseur.', 'Ajoutez le contrat si applicable.', 'Joignez les annexes.'], ['أنشئ المورد.', 'أضف العقد عند الحاجة.', 'أرفق الملاحق.'], 'Organisation et résidence.', 'مؤسسة وإقامة.', 'Fournisseur disponible.', 'مورد متاح.', 'Dupliquer un fournisseur ou renouveler en écrasant.', 'تكرار مورد أو تجديد العقد بالاستبدال.', 'Factures, engagements et maintenance.', 'الفواتير والالتزامات والصيانة.'),
        'setup-accounting' => $check('financial-setup', 'Configurer exercice et comptabilité', 'ضبط السنة والمحاسبة', 'Définir la période financière et le cadre comptable.', 'تحديد الفترة المالية والإطار المحاسبي.', 'Comptable ou administrateur autorisé.', 'محاسب أو مدير مخول.', 'Finance > Exercices; Comptabilité.', 'المالية > السنوات؛ المحاسبة.', 'Dates, régime, journaux, périodes et comptes.', 'التواريخ والنظام واليوميات والفترات والحسابات.', ['Créez/ouvrez l’exercice.', 'Adoptez le cadre.', 'Configurez journaux et périodes.', 'Contrôlez les règles.'], ['أنشئ وافتح السنة.', 'اعتمد الإطار.', 'اضبط اليوميات والفترات.', 'راجع القواعد.'], 'Résidence active.', 'إقامة نشطة.', 'Exercice disponible.', 'سنة متاحة.', 'Confondre fermeture d’exercice et clôture comptable.', 'الخلط بين إغلاق السنة والإقفال المحاسبي.', 'Budgets et opérations financières.', 'الميزانيات والعمليات المالية.'),
        'setup-accounts' => $check('financial-setup', 'Créer banque ou caisse et soldes d’ouverture', 'إنشاء البنك أو الصندوق وأرصدة الافتتاح', 'Identifier où entrent et sortent les fonds.', 'تحديد مكان دخول الأموال وخروجها.', 'Gestionnaire des comptes/comptable.', 'مسير الحسابات أو المحاسب.', 'Finance > Comptes; Comptabilité > Ouverture.', 'المالية > الحسابات؛ المحاسبة > الافتتاح.', 'Nom, type, références; lignes d’ouverture équilibrées.', 'الاسم والنوع والمراجع؛ بنود افتتاح متوازنة.', ['Créez les comptes.', 'Préparez le lot d’ouverture si nécessaire.', 'Faites revoir puis comptabiliser.'], ['أنشئ الحسابات.', 'حضّر دفعة الافتتاح عند الحاجة.', 'راجعها ثم رحّلها.'], 'Exercice/cadre configuré.', 'سنة وإطار مضبوطان.', 'Compte financier actif.', 'حساب مالي نشط.', 'Créer le solde avec un faux encaissement.', 'إنشاء الرصيد بدفعة وهمية.', 'Paiements et règlements.', 'الدفعات والتسويات.'),
        'setup-allocations' => $check('allocation-keys', 'Définir les clés de répartition', 'تحديد مفاتيح التوزيع', 'Répartir les montants entre lots.', 'توزيع المبالغ على الوحدات.', 'Gestionnaire des répartitions.', 'مسير التوزيعات.', 'Allocations.', 'التوزيعات.', 'Nom de clé et valeur de chaque lot.', 'اسم المفتاح وقيمة كل وحدة.', ['Créez la clé.', 'Complétez tous les lots.', 'Vérifiez le total.', 'Associez les catégories.'], ['أنشئ المفتاح.', 'أكمل كل الوحدات.', 'راجع المجموع.', 'اربط الفئات.'], 'Lots actifs.', 'وحدات نشطة.', 'Clé disponible et complète.', 'مفتاح متاح ومكتمل.', 'Laisser des lots sans valeur.', 'ترك وحدات بلا قيمة.', 'Appels de fonds fiables.', 'نداءات أموال موثوقة.'),
        'setup-charges' => $check('financial-setup', 'Créer les catégories de charges', 'إنشاء فئات المصاريف', 'Classer et distribuer charges et dépenses.', 'تصنيف وتوزيع المصاريف.', 'Gestionnaire financier.', 'المسير المالي.', 'Finance > Catégories.', 'المالية > الفئات.', 'Libellé et clé par défaut.', 'التسمية والمفتاح الافتراضي.', ['Créez les catégories.', 'Choisissez la clé.', 'Contrôlez leur activation.'], ['أنشئ الفئات.', 'اختر المفتاح.', 'راجع التفعيل.'], 'Clés de répartition.', 'مفاتيح التوزيع.', 'Catégories actives.', 'فئات نشطة.', 'Choisir une clé sans valeurs complètes.', 'اختيار مفتاح ناقص.', 'Budgets, appels et factures.', 'الميزانيات والنداءات والفواتير.'),
        'setup-budget' => $check('budgets', 'Préparer le budget', 'إعداد الميزانية', 'Planifier les dépenses de l’exercice.', 'تخطيط مصاريف السنة.', 'Gestionnaire et approbateur.', 'المسير والمصادق.', 'Dépenses > Budgets.', 'المصاريف > الميزانيات.', 'Exercice, lignes, catégories, montants MAD.', 'السنة والبنود والفئات والمبالغ بالدرهم.', ['Créez le brouillon.', 'Ajoutez les lignes.', 'Contrôlez puis approuvez.'], ['أنشئ المسودة.', 'أضف البنود.', 'راجع ثم اعتمد.'], 'Exercice et catégories.', 'سنة وفئات.', 'Budget approuvé ou prêt.', 'ميزانية معتمدة أو جاهزة.', 'Croire que le budget crée les dettes.', 'اعتبار الميزانية منشئة للديون.', 'Pilotage et appels de fonds.', 'التسيير ونداءات الأموال.'),
        'issue-fund-call' => $check('fund-calls', 'Émettre le premier appel de fonds', 'إصدار أول نداء أموال', 'Créer les créances par lot.', 'إنشاء المستحقات لكل وحدة.', 'Créateur puis valideur autorisé.', 'منشئ ثم مصادق مخول.', 'Finance > Appels de fonds.', 'المالية > نداءات الأموال.', 'Dates, lignes, cible, méthode, montant.', 'التواريخ والبنود والهدف والطريقة والمبلغ.', ['Créez le brouillon.', 'Contrôlez la distribution.', 'Validez.', 'Générez les documents.'], ['أنشئ المسودة.', 'راجع التوزيع.', 'اعتمد.', 'أنشئ المستندات.'], 'Lots, propriétaires, exercice, catégories et clés.', 'وحدات وملاك وسنة وفئات ومفاتيح.', 'Charges par lot.', 'مستحقات حسب الوحدة.', 'Valider sans vérifier les lots ciblés.', 'الاعتماد دون مراجعة الوحدات المستهدفة.', 'Encaissements, impayés et relevés.', 'التحصيل والمتأخرات والكشوف.'),
        'record-payments' => $check('payments-credit', 'Enregistrer paiements et affectations', 'تسجيل الدفعات والتخصيصات', 'Constater les encaissements et solder les charges.', 'إثبات التحصيل وتسديد المستحقات.', 'Agent financier autorisé.', 'موظف مالي مخول.', 'Finance > Paiements.', 'المالية > الدفعات.', 'Payeur, date, montant, mode, compte, référence.', 'الدافع والتاريخ والمبلغ والطريقة والحساب والمرجع.', ['Saisissez.', 'Validez.', 'Affectez le crédit.', 'Contrôlez le reçu et le relevé.'], ['أدخل.', 'اعتمد.', 'خصص الرصيد.', 'راجع الوصل والكشف.'], 'Compte, exercice, charges.', 'حساب وسنة ومستحقات.', 'Paiement validé et affecté.', 'دفعة معتمدة ومخصصة.', 'Affecter un paiement inconnu au hasard.', 'تخصيص دفعة مجهولة عشوائيا.', 'Recouvrement et rapprochement.', 'التحصيل والمطابقة.'),
        'supplier-operations' => $check('supplier-workflow', 'Traiter factures et règlements fournisseurs', 'معالجة فواتير وتسويات الموردين', 'Constater puis payer les dettes.', 'إثبات الديون ثم أداؤها.', 'Équipe dépenses/comptable.', 'فريق المصاريف أو المحاسب.', 'Dépenses > Factures / Exigibles / Règlements.', 'المصاريف > الفواتير / المستحقات / التسويات.', 'Fournisseur, dates, lignes, pièce, compte, affectation.', 'المورد والتواريخ والبنود والمرفق والحساب والتخصيص.', ['Saisissez et validez la facture.', 'Contrôlez l’exigible.', 'Créez et validez le règlement.'], ['أدخل واعتمد الفاتورة.', 'راجع المستحق.', 'أنشئ واعتمد التسوية.'], 'Fournisseur, exercice, catégorie, compte.', 'مورد وسنة وفئة وحساب.', 'Dette et paiement tracés.', 'دين وأداء موثقان.', 'Supprimer une pièce validée.', 'حذف دليل معتمد.', 'Rapports fournisseurs et comptabilité.', 'تقارير الموردين والمحاسبة.'),
        'reconcile-close' => $check('accounting-closing-workflow', 'Rapprocher et clôturer', 'المطابقة والإقفال', 'Vérifier l’exhaustivité avant de figer.', 'التحقق من الاكتمال قبل التجميد.', 'Comptable et approbateurs.', 'المحاسب والمصادقون.', 'Comptabilité > Rapports / Clôture.', 'المحاسبة > التقارير / الإقفال.', 'Exercice, période, justification et contrôles.', 'السنة والفترة والتبرير والضوابط.', ['Rapprochez tous les sous-ledgers.', 'Corrigez les écarts.', 'Préparez.', 'Faites revoir/approuver.', 'Exécutez.'], ['طابق كل السجلات الفرعية.', 'صحح الفروق.', 'حضّر.', 'راجع واعتمد.', 'نفّذ.'], 'Opérations validées et mappings fiables.', 'عمليات معتمدة وربط موثوق.', 'Période ou exercice clôturé avec preuves.', 'فترة أو سنة مقفلة بأدلتها.', 'Clôturer avec des écarts non expliqués.', 'الإقفال مع فروق غير مفسرة.', 'États définitifs et report à nouveau.', 'القوائم النهائية والترحيل.'),
        'publish-govern' => $check('documents-communication-workflow', 'Publier, gouverner et suivre la conformité', 'النشر والحكامة وتتبع الامتثال', 'Mettre les portails et obligations en exploitation.', 'تشغيل البوابات والالتزامات.', 'Gestionnaires et rôles spécialisés.', 'المسيرون والأدوار المختصة.', 'Documents / Annonces / Gouvernance / Conformité.', 'المستندات / الإعلانات / الحكامة / الامتثال.', 'Audience, versions, dates, règles, preuves.', 'الجمهور والإصدارات والتواريخ والقواعد والأدلة.', ['Publiez les documents utiles.', 'Créez les communications.', 'Préparez les assemblées.', 'Assignez les obligations.', 'Vérifiez les portails et exports.'], ['انشر المستندات.', 'أنشئ التواصل.', 'حضّر الجموع.', 'عيّن الالتزامات.', 'راجع البوابات والتصديرات.'], 'Résidence, contacts et droits configurés.', 'إقامة واتصالات وصلاحيات مضبوطة.', 'Exploitation complète et contrôlée.', 'تشغيل كامل ومراقب.', 'Confondre annonce et avis formel.', 'الخلط بين الإعلان والتبليغ الرسمي.', 'Portails, registres, rapports et audit.', 'البوابات والسجلات والتقارير والتدقيق.'),
    ],
];
